// Enhanced hiragana data with romaji and meaning structure
const hiraganaData = {
    //  a            i           u            e            o
    'あ': { romaji: 'a', meaning: '' },   'い': { romaji: 'i', meaning: '' },   'う': { romaji: 'u', meaning: '' },   'え': { romaji: 'e', meaning: '' },   'お': { romaji: 'o', meaning: '' },
    //  k-series
    'か': { romaji: 'ka', meaning: '' },  'き': { romaji: 'ki', meaning: '' },  'く': { romaji: 'ku', meaning: '' },  'け': { romaji: 'ke', meaning: '' },  'こ': { romaji: 'ko', meaning: '' },
    'が': { romaji: 'ga', meaning: '' },  'ぎ': { romaji: 'gi', meaning: '' },  'ぐ': { romaji: 'gu', meaning: '' },  'げ': { romaji: 'ge', meaning: '' },  'ご': { romaji: 'go', meaning: '' },
    //  s-series
    'さ': { romaji: 'sa', meaning: '' },  'し': { romaji: 'shi', meaning: '' }, 'す': { romaji: 'su', meaning: '' },  'せ': { romaji: 'se', meaning: '' },  'そ': { romaji: 'so', meaning: '' },
    'ざ': { romaji: 'za', meaning: '' },  'じ': { romaji: 'ji', meaning: '' },  'ず': { romaji: 'zu', meaning: '' },  'ぜ': { romaji: 'ze', meaning: '' },  'ぞ': { romaji: 'zo', meaning: '' },
    //  t-series
    'た': { romaji: 'ta', meaning: '' },  'ち': { romaji: 'chi', meaning: '' }, 'つ': { romaji: 'tsu', meaning: '' }, 'て': { romaji: 'te', meaning: '' },  'と': { romaji: 'to', meaning: '' },
    'だ': { romaji: 'da', meaning: '' },  'ぢ': { romaji: 'ji', meaning: '' },  'づ': { romaji: 'zu', meaning: '' },  'で': { romaji: 'de', meaning: '' },  'ど': { romaji: 'do', meaning: '' },
    //  n-series
    'な': { romaji: 'na', meaning: '' },  'に': { romaji: 'ni', meaning: '' },  'ぬ': { romaji: 'nu', meaning: '' },  'ね': { romaji: 'ne', meaning: '' },  'の': { romaji: 'no', meaning: '' },
    //  h-series
    'は': { romaji: 'ha', meaning: '' },  'ひ': { romaji: 'hi', meaning: '' },  'ふ': { romaji: 'fu', meaning: '' },  'へ': { romaji: 'he', meaning: '' },  'ほ': { romaji: 'ho', meaning: '' },
    'ば': { romaji: 'ba', meaning: '' },  'び': { romaji: 'bi', meaning: '' },  'ぶ': { romaji: 'bu', meaning: '' },  'べ': { romaji: 'be', meaning: '' },  'ぼ': { romaji: 'bo', meaning: '' },
    'ぱ': { romaji: 'pa', meaning: '' },  'ぴ': { romaji: 'pi', meaning: '' },  'ぷ': { romaji: 'pu', meaning: '' },  'ぺ': { romaji: 'pe', meaning: '' },  'ぽ': { romaji: 'po', meaning: '' },
    //  m-series
    'ま': { romaji: 'ma', meaning: '' },  'み': { romaji: 'mi', meaning: '' },  'む': { romaji: 'mu', meaning: '' },  'め': { romaji: 'me', meaning: '' },  'も': { romaji: 'mo', meaning: '' },
    //  y-series
    'や': { romaji: 'ya', meaning: '' },                                         'ゆ': { romaji: 'yu', meaning: '' },                                         'よ': { romaji: 'yo', meaning: '' },
    //  r-series
    'ら': { romaji: 'ra', meaning: '' },  'り': { romaji: 'ri', meaning: '' },  'る': { romaji: 'ru', meaning: '' },  'れ': { romaji: 're', meaning: '' },  'ろ': { romaji: 'ro', meaning: '' },
    'わ': { romaji: 'wa', meaning: '' },                                                                                                                   'を': { romaji: 'wo', meaning: '' },
    'ん': { romaji: 'n', meaning: '' },

    // Yoon (contracted sounds)
    'きゃ': { romaji: 'kya', meaning: '' },          'きゅ': { romaji: 'kyu', meaning: '' },             'きょ': { romaji: 'kyo', meaning: '' },
    'しゃ': { romaji: 'sha', meaning: '' },          'しゅ': { romaji: 'shu', meaning: '' },             'しょ': { romaji: 'sho', meaning: '' },
    'ちゃ': { romaji: 'cha', meaning: '' },          'ちゅ': { romaji: 'chu', meaning: '' },             'ちょ': { romaji: 'cho', meaning: '' },
    'にゃ': { romaji: 'nya', meaning: '' },          'にゅ': { romaji: 'nyu', meaning: '' },             'にょ': { romaji: 'nyo', meaning: '' },
    'ひゃ': { romaji: 'hya', meaning: '' },          'ひゅ': { romaji: 'hyu', meaning: '' },             'ひょ': { romaji: 'hyo', meaning: '' },
    'みゃ': { romaji: 'mya', meaning: '' },          'みゅ': { romaji: 'myu', meaning: '' },             'みょ': { romaji: 'myo', meaning: '' },
    'りゃ': { romaji: 'rya', meaning: '' },          'りゅ': { romaji: 'ryu', meaning: '' },             'りょ': { romaji: 'ryo', meaning: '' },
    'ぎゃ': { romaji: 'gya', meaning: '' },          'ぎゅ': { romaji: 'gyu', meaning: '' },             'ぎょ': { romaji: 'gyo', meaning: '' },
    'じゃ': { romaji: 'ja', meaning: '' },           'じゅ': { romaji: 'ju', meaning: '' },              'じょ': { romaji: 'jo', meaning: '' },
    'びゃ': { romaji: 'bya', meaning: '' },          'びゅ': { romaji: 'byu', meaning: '' },             'びょ': { romaji: 'byo', meaning: '' },
    'ぴゃ': { romaji: 'pya', meaning: '' },          'ぴゅ': { romaji: 'pyu', meaning: '' },             'ぴょ': { romaji: 'pyo', meaning: '' }
};

// Difficulty-based word data
const hiraganaWordData = {
    easy: {
        // Original words (katakana words removed)
        'あめ': { romaji: 'ame', meaning: 'rain' },
        'いぬ': { romaji: 'inu', meaning: 'dog' },
        'うみ': { romaji: 'umi', meaning: 'sea' },
        'えき': { romaji: 'eki', meaning: 'station' },
        'おちゃ': { romaji: 'ocha', meaning: 'tea' },
        'かお': { romaji: 'kao', meaning: 'face' },
        'き': { romaji: 'ki', meaning: 'tree' },
        'くち': { romaji: 'kuchi', meaning: 'mouth' },
        'け': { romaji: 'ke', meaning: 'hair' },
        'こえ': { romaji: 'koe', meaning: 'voice' },
        'さかな': { romaji: 'sakana', meaning: 'fish' },
        'そら': { romaji: 'sora', meaning: 'sky' },
        'て': { romaji: 'te', meaning: 'hand' },
        'なまえ': { romaji: 'namae', meaning: 'name' },
        'ほん': { romaji: 'hon', meaning: 'book' },
        'みず': { romaji: 'mizu', meaning: 'water' },
        'やま': { romaji: 'yama', meaning: 'mountain' },
        'よる': { romaji: 'yoru', meaning: 'night' },
        'わたし': { romaji: 'watashi', meaning: 'I' },
        'ひ': { romaji: 'hi', meaning: 'fire' },
        'ねこ': { romaji: 'neko', meaning: 'cat' },
        'あさ': { romaji: 'asa', meaning: 'morning' },
        'ひる': { romaji: 'hiru', meaning: 'noon' },
        'つき': { romaji: 'tsuki', meaning: 'moon' },
        'はな': { romaji: 'hana', meaning: 'flower' },
        'め': { romaji: 'me', meaning: 'eye' },
        'みみ': { romaji: 'mimi', meaning: 'ear' },
        'あし': { romaji: 'ashi', meaning: 'foot' },
        'いえ': { romaji: 'ie', meaning: 'house' },
        'とり': { romaji: 'tori', meaning: 'bird' },
        'かぜ': { romaji: 'kaze', meaning: 'wind' },
        'ゆき': { romaji: 'yuki', meaning: 'snow' },
        'はる': { romaji: 'haru', meaning: 'spring' },
        'なつ': { romaji: 'natsu', meaning: 'summer' },
        'あき': { romaji: 'aki', meaning: 'autumn' },
        'ふゆ': { romaji: 'fuyu', meaning: 'winter' },
        'くも': { romaji: 'kumo', meaning: 'cloud' },
        'いし': { romaji: 'ishi', meaning: 'stone' },
        'かわ': { romaji: 'kawa', meaning: 'river' },
        'はし': { romaji: 'hashi', meaning: 'bridge' },
        'みち': { romaji: 'michi', meaning: 'road' },
        'まち': { romaji: 'machi', meaning: 'town' },
        'まど': { romaji: 'mado', meaning: 'window' },
        'いす': { romaji: 'isu', meaning: 'chair' },
        'かみ': { romaji: 'kami', meaning: 'paper' },
        'はこ': { romaji: 'hako', meaning: 'box' },

        // Body parts
        'はな': { romaji: 'hana', meaning: 'nose' },
        'は': { romaji: 'ha', meaning: 'tooth' },
        'した': { romaji: 'shita', meaning: 'tongue' },
        'くび': { romaji: 'kubi', meaning: 'neck' },
        'ゆび': { romaji: 'yubi', meaning: 'finger' },
        'つめ': { romaji: 'tsume', meaning: 'nail' },
        'ひざ': { romaji: 'hiza', meaning: 'knee' },
        'ひじ': { romaji: 'hiji', meaning: 'elbow' },
        'かた': { romaji: 'kata', meaning: 'shoulder' },

        // Food and drink (katakana removed)
        'にく': { romaji: 'niku', meaning: 'meat' },
        'いも': { romaji: 'imo', meaning: 'potato' },
        'あめ': { romaji: 'ame', meaning: 'candy' },

        // Clothing
        'ふく': { romaji: 'fuku', meaning: 'clothes' },
        'くつ': { romaji: 'kutsu', meaning: 'shoes' },

        // Household items
        'かがみ': { romaji: 'kagami', meaning: 'mirror' },
        'かさ': { romaji: 'kasa', meaning: 'umbrella' },

        // Colors
        'あか': { romaji: 'aka', meaning: 'red' },
        'あお': { romaji: 'ao', meaning: 'blue' },
        'しろ': { romaji: 'shiro', meaning: 'white' },
        'くろ': { romaji: 'kuro', meaning: 'black' },

        // Numbers (1-10)
        'いち': { romaji: 'ichi', meaning: 'one' },
        'に': { romaji: 'ni', meaning: 'two' },
        'さん': { romaji: 'san', meaning: 'three' },
        'よん': { romaji: 'yon', meaning: 'four' },
        'ご': { romaji: 'go', meaning: 'five' },
        'ろく': { romaji: 'roku', meaning: 'six' },
        'なな': { romaji: 'nana', meaning: 'seven' },
        'はち': { romaji: 'hachi', meaning: 'eight' },
        'きゅう': { romaji: 'kyuu', meaning: 'nine' },
        'じゅう': { romaji: 'juu', meaning: 'ten' },

        // Transportation
        'くるま': { romaji: 'kuruma', meaning: 'car' },
        'ふね': { romaji: 'fune', meaning: 'ship' },

        // Animals
        'うし': { romaji: 'ushi', meaning: 'cow' },
        'うま': { romaji: 'uma', meaning: 'horse' },
        'ぶた': { romaji: 'buta', meaning: 'pig' },
        'うさぎ': { romaji: 'usagi', meaning: 'rabbit' },
        'かめ': { romaji: 'kame', meaning: 'turtle' },
        'へび': { romaji: 'hebi', meaning: 'snake' },
        'かえる': { romaji: 'kaeru', meaning: 'frog' },
        'むし': { romaji: 'mushi', meaning: 'bug' },

        // School supplies
        'のり': { romaji: 'nori', meaning: 'glue' },

        // Common verbs (dictionary form)
        'たべる': { romaji: 'taberu', meaning: 'eat' },
        'のむ': { romaji: 'nomu', meaning: 'drink' },
        'みる': { romaji: 'miru', meaning: 'see' },
        'きく': { romaji: 'kiku', meaning: 'listen' },
        'よむ': { romaji: 'yomu', meaning: 'read' },
        'かく': { romaji: 'kaku', meaning: 'write' },
        'いく': { romaji: 'iku', meaning: 'go' },
        'くる': { romaji: 'kuru', meaning: 'come' },
        'ねる': { romaji: 'neru', meaning: 'sleep' },

        // Common adjectives
        'いい': { romaji: 'ii', meaning: 'good' },
        'わるい': { romaji: 'warui', meaning: 'bad' },
        'あつい': { romaji: 'atsui', meaning: 'hot' },
        'さむい': { romaji: 'samui', meaning: 'cold' },

        // Time words
        'きょう': { romaji: 'kyou', meaning: 'today' },
        'きのう': { romaji: 'kinou', meaning: 'yesterday' },
        'いま': { romaji: 'ima', meaning: 'now' },
        'まえ': { romaji: 'mae', meaning: 'before' },
        'あと': { romaji: 'ato', meaning: 'after' },

        // Common objects
        'かぎ': { romaji: 'kagi', meaning: 'key' },

        // NEW ADDITIONS - Simple hiragana words (3 characters or less)
        /*'あに': { romaji: 'ani', meaning: 'older brother' },
        'あね': { romaji: 'ane', meaning: 'older sister' },
        'おと': { romaji: 'oto', meaning: 'sound' },
        'おに': { romaji: 'oni', meaning: 'demon' },
        'かぜ': { romaji: 'kaze', meaning: 'wind' },
        'きた': { romaji: 'kita', meaning: 'north' },
        'きぬ': { romaji: 'kinu', meaning: 'silk' },
        'くま': { romaji: 'kuma', meaning: 'bear' },
        'こめ': { romaji: 'kome', meaning: 'rice' },
        'しお': { romaji: 'shio', meaning: 'salt' },
        'すし': { romaji: 'sushi', meaning: 'sushi' },
        'たけ': { romaji: 'take', meaning: 'bamboo' },
        'つち': { romaji: 'tsuchi', meaning: 'soil' },
        'とら': { romaji: 'tora', meaning: 'tiger' },
        'なみ': { romaji: 'nami', meaning: 'wave' },
        'のり': { romaji: 'nori', meaning: 'seaweed' },
        'はち': { romaji: 'hachi', meaning: 'bee' },
        'ひも': { romaji: 'himo', meaning: 'string' },
        'ふみ': { romaji: 'fumi', meaning: 'letter' },
        'ほし': { romaji: 'hoshi', meaning: 'star' },
        'みそ': { romaji: 'miso', meaning: 'miso' },
        'もも': { romaji: 'momo', meaning: 'peach' },
        'やく': { romaji: 'yaku', meaning: 'medicine' },
        'ゆめ': { romaji: 'yume', meaning: 'dream' },
        'らく': { romaji: 'raku', meaning: 'easy' },
        'わに': { romaji: 'wani', meaning: 'crocodile' },
        'あぶ': { romaji: 'abu', meaning: 'horsefly' },
        'いと': { romaji: 'ito', meaning: 'thread' },
        'うた': { romaji: 'uta', meaning: 'song' },
        'えび': { romaji: 'ebi', meaning: 'shrimp' },
        'おび': { romaji: 'obi', meaning: 'belt' },
        'かに': { romaji: 'kani', meaning: 'crab' },
        'きり': { romaji: 'kiri', meaning: 'fog' },
        'くし': { romaji: 'kushi', meaning: 'comb' },
        'けが': { romaji: 'kega', meaning: 'injury' },
        'こし': { romaji: 'koshi', meaning: 'waist' },
        'すみ': { romaji: 'sumi', meaning: 'charcoal' },
        'たき': { romaji: 'taki', meaning: 'waterfall' },
        'つぼ': { romaji: 'tsubo', meaning: 'jar' },
        'なべ': { romaji: 'nabe', meaning: 'pot' },
        'のこ': { romaji: 'noko', meaning: 'saw' },
        'はり': { romaji: 'hari', meaning: 'needle' },
        'ひげ': { romaji: 'hige', meaning: 'beard' },
        'ふた': { romaji: 'futa', meaning: 'lid' },
        'へた': { romaji: 'heta', meaning: 'poor at' },
        'ほね': { romaji: 'hone', meaning: 'bone' },
        'みみ': { romaji: 'mimi', meaning: 'ear' },
        'むね': { romaji: 'mune', meaning: 'chest' },
        'やね': { romaji: 'yane', meaning: 'roof' },
        'よい': { romaji: 'yoi', meaning: 'good' },
        'らし': { romaji: 'rashi', meaning: 'seems' },
        'わた': { romaji: 'wata', meaning: 'cotton' }*/
    },
    normal: {
        'こんにちは': { romaji: 'konnichiwa', meaning: 'hello' },
        'ありがとう': { romaji: 'arigatou', meaning: 'thank you' },
        'おはよう': { romaji: 'ohayou', meaning: 'good morning' },
        'おやすみ': { romaji: 'oyasumi', meaning: 'good night' },
        'こんばんは': { romaji: 'konbanwa', meaning: 'good evening' },
        'さようなら': { romaji: 'sayounara', meaning: 'goodbye' },
        'すみません': { romaji: 'sumimasen', meaning: 'excuse me' },
        'ともだち': { romaji: 'tomodachi', meaning: 'friend' },
        'たのしい': { romaji: 'tanoshii', meaning: 'fun' },
        'しあわせ': { romaji: 'shiawase', meaning: 'happy' },
        'かなしい': { romaji: 'kanashii', meaning: 'sad' },
        'きんようび': { romaji: 'kinyoubi', meaning: 'Friday' },
        'どようび': { romaji: 'doyoubi', meaning: 'Saturday' },
        'にちようび': { romaji: 'nichiyoubi', meaning: 'Sunday' },
        'げつようび': { romaji: 'getsuyoubi', meaning: 'Monday' },
        'かようび': { romaji: 'kayoubi', meaning: 'Tuesday' },
        'すいようび': { romaji: 'suiyoubi', meaning: 'Wednesday' },
        'もくようび': { romaji: 'mokuyoubi', meaning: 'Thursday' },
        'せんしゅう': { romaji: 'senshuu', meaning: 'last week' },
        'らいしゅう': { romaji: 'raishuu', meaning: 'next week' },
        'きょう': { romaji: 'kyou', meaning: 'today' },
        'きのう': { romaji: 'kinou', meaning: 'yesterday' },
        'あした': { romaji: 'ashita', meaning: 'tomorrow' },
        
        /*
        'がっこう': { romaji: 'gakkou', meaning: 'school' },
        'しごと': { romaji: 'shigoto', meaning: 'work' },
        'でんわ': { romaji: 'denwa', meaning: 'telephone' },
        'たべもの': { romaji: 'tabemono', meaning: 'food' },
        'かぞく': { romaji: 'kazoku', meaning: 'family' },
        'びょういん': { romaji: 'byouin', meaning: 'hospital' },
        'ぎんこう': { romaji: 'ginkou', meaning: 'bank' },
        'でんしゃ': { romaji: 'densha', meaning: 'train' },
        'ひこうき': { romaji: 'hikouki', meaning: 'airplane' },
        'しんぶん': { romaji: 'shinbun', meaning: 'newspaper' },
        'てがみ': { romaji: 'tegami', meaning: 'letter' },
        'じかん': { romaji: 'jikan', meaning: 'time' },
        'ばんごはん': { romaji: 'bangohan', meaning: 'dinner' },
        // New normal words
        'あさごはん': { romaji: 'asagohan', meaning: 'breakfast' },
        'ひるごはん': { romaji: 'hirugohan', meaning: 'lunch' },
        'りょうり': { romaji: 'ryouri', meaning: 'cooking' },
        'みせ': { romaji: 'mise', meaning: 'shop' },
        'おかね': { romaji: 'okane', meaning: 'money' },
        'しゅみ': { romaji: 'shumi', meaning: 'hobby' },
        'すぽーつ': { romaji: 'supootsu', meaning: 'sports' },
        'おんがく': { romaji: 'ongaku', meaning: 'music' },
        'えいが': { romaji: 'eiga', meaning: 'movie' },
        'てれび': { romaji: 'terebi', meaning: 'television' },
        'でんき': { romaji: 'denki', meaning: 'electricity' },
        'せんたく': { romaji: 'sentaku', meaning: 'laundry' },
        'そうじ': { romaji: 'souji', meaning: 'cleaning' },
        'かいもの': { romaji: 'kaimono', meaning: 'shopping' },
        'りょこう': { romaji: 'ryokou', meaning: 'travel' },
        'やすみ': { romaji: 'yasumi', meaning: 'rest/holiday' },
        'しゅっしん': { romaji: 'shusshin', meaning: 'hometown' },
        'くに': { romaji: 'kuni', meaning: 'country' },
        'げんき': { romaji: 'genki', meaning: 'healthy/energetic' },
        'びょうき': { romaji: 'byouki', meaning: 'illness' },
        'くすり': { romaji: 'kusuri', meaning: 'medicine' },
        'いしゃ': { romaji: 'isha', meaning: 'doctor' },
        'てんき': { romaji: 'tenki', meaning: 'weather' },
        'あたたかい': { romaji: 'atatakai', meaning: 'warm' },
        'すずしい': { romaji: 'suzushii', meaning: 'cool' },
        'おもしろい': { romaji: 'omoshiroi', meaning: 'interesting' },
        'むずかしい': { romaji: 'muzukashii', meaning: 'difficult' },
        'やさしい': { romaji: 'yasashii', meaning: 'easy/kind' },
        'あたらしい': { romaji: 'atarashii', meaning: 'new' },
        'ふるい': { romaji: 'furui', meaning: 'old' }*/
    },
    hard: {
        'はじめまして': { romaji: 'hajimemashite', meaning: 'nice to meet you' },
        'いただきます': { romaji: 'itadakimasu', meaning: 'before eating' },
        'ごちそうさま': { romaji: 'gochisousama', meaning: 'after eating' },
        'おつかれさま': { romaji: 'otsukaresama', meaning: 'good work' },
        'しつれいします': { romaji: 'shitsurei shimasu', meaning: 'excuse me' },
        'だいがく': { romaji: 'daigaku', meaning: 'university' },
        'としょかん': { romaji: 'toshokan', meaning: 'library' },
        'びじゅつかん': { romaji: 'bijutsukan', meaning: 'art museum' },
        'きょうしつ': { romaji: 'kyoushitsu', meaning: 'classroom' },
        'せんせい': { romaji: 'sensei', meaning: 'teacher' },
        'がくせい': { romaji: 'gakusei', meaning: 'student' },
        'しゅくだい': { romaji: 'shukudai', meaning: 'homework' },
        'しけん': { romaji: 'shiken', meaning: 'exam' },
        'けんきゅう': { romaji: 'kenkyuu', meaning: 'research' },
        'かいぎ': { romaji: 'kaigi', meaning: 'meeting' },
        'やくそく': { romaji: 'yakusoku', meaning: 'promise' },
        'しんぱい': { romaji: 'shinpai', meaning: 'worry' },
        'あんぜん': { romaji: 'anzen', meaning: 'safety' },
        'けいけん': { romaji: 'keiken', meaning: 'experience' },
        'もんだい': { romaji: 'mondai', meaning: 'problem' }
    }
};
// Enhanced katakana data with romaji and meaning structure
const katakanaData = {
    //  a            i           u            e            o
    'ア': { romaji: 'a', meaning: '' },   'イ': { romaji: 'i', meaning: '' },   'ウ': { romaji: 'u', meaning: '' },   'エ': { romaji: 'e', meaning: '' },   'オ': { romaji: 'o', meaning: '' },
    //  k-series
    'カ': { romaji: 'ka', meaning: '' },  'キ': { romaji: 'ki', meaning: '' },  'ク': { romaji: 'ku', meaning: '' },  'ケ': { romaji: 'ke', meaning: '' },  'コ': { romaji: 'ko', meaning: '' },
    'ガ': { romaji: 'ga', meaning: '' },  'ギ': { romaji: 'gi', meaning: '' },  'グ': { romaji: 'gu', meaning: '' },  'ゲ': { romaji: 'ge', meaning: '' },  'ゴ': { romaji: 'go', meaning: '' },
    //  s-series
    'サ': { romaji: 'sa', meaning: '' },  'シ': { romaji: 'shi', meaning: '' }, 'ス': { romaji: 'su', meaning: '' },  'セ': { romaji: 'se', meaning: '' },  'ソ': { romaji: 'so', meaning: '' },
    'ザ': { romaji: 'za', meaning: '' },  'ジ': { romaji: 'ji', meaning: '' },  'ズ': { romaji: 'zu', meaning: '' },  'ゼ': { romaji: 'ze', meaning: '' },  'ゾ': { romaji: 'zo', meaning: '' },
    //  t-series
    'タ': { romaji: 'ta', meaning: '' },  'チ': { romaji: 'chi', meaning: '' }, 'ツ': { romaji: 'tsu', meaning: '' }, 'テ': { romaji: 'te', meaning: '' },  'ト': { romaji: 'to', meaning: '' },
    'ダ': { romaji: 'da', meaning: '' },  'ヂ': { romaji: 'ji', meaning: '' },  'ヅ': { romaji: 'zu', meaning: '' },  'デ': { romaji: 'de', meaning: '' },  'ド': { romaji: 'do', meaning: '' },
    //  n-series
    'ナ': { romaji: 'na', meaning: '' },  'ニ': { romaji: 'ni', meaning: '' },  'ヌ': { romaji: 'nu', meaning: '' },  'ネ': { romaji: 'ne', meaning: '' },  'ノ': { romaji: 'no', meaning: '' },
    //  h-series
    'ハ': { romaji: 'ha', meaning: '' },  'ヒ': { romaji: 'hi', meaning: '' },  'フ': { romaji: 'fu', meaning: '' },  'ヘ': { romaji: 'he', meaning: '' },  'ホ': { romaji: 'ho', meaning: '' },
    'バ': { romaji: 'ba', meaning: '' },  'ビ': { romaji: 'bi', meaning: '' },  'ブ': { romaji: 'bu', meaning: '' },  'ベ': { romaji: 'be', meaning: '' },  'ボ': { romaji: 'bo', meaning: '' },
    'パ': { romaji: 'pa', meaning: '' },  'ピ': { romaji: 'pi', meaning: '' },  'プ': { romaji: 'pu', meaning: '' },  'ペ': { romaji: 'pe', meaning: '' },  'ポ': { romaji: 'po', meaning: '' },
    //  m-series
    'マ': { romaji: 'ma', meaning: '' },  'ミ': { romaji: 'mi', meaning: '' },  'ム': { romaji: 'mu', meaning: '' },  'メ': { romaji: 'me', meaning: '' },  'モ': { romaji: 'mo', meaning: '' },
    //  y-series
    'ヤ': { romaji: 'ya', meaning: '' },                                         'ユ': { romaji: 'yu', meaning: '' },                                         'ヨ': { romaji: 'yo', meaning: '' },
    //  r-series
    'ラ': { romaji: 'ra', meaning: '' },  'リ': { romaji: 'ri', meaning: '' },  'ル': { romaji: 'ru', meaning: '' },  'レ': { romaji: 're', meaning: '' },  'ロ': { romaji: 'ro', meaning: '' },
    'ワ': { romaji: 'wa', meaning: '' },  'ヰ': { romaji: 'wi', meaning: '' },  'ヱ': { romaji: 'we', meaning: '' },  'ヲ': { romaji: 'wo', meaning: '' },
    'ン': { romaji: 'n', meaning: '' },

    // Yoon (contracted sounds)
    'キャ': { romaji: 'kya', meaning: '' },          'キュ': { romaji: 'kyu', meaning: '' },             'キョ': { romaji: 'kyo', meaning: '' },
    'シャ': { romaji: 'sha', meaning: '' },          'シュ': { romaji: 'shu', meaning: '' },             'ショ': { romaji: 'sho', meaning: '' },
    'チャ': { romaji: 'cha', meaning: '' },          'チュ': { romaji: 'chu', meaning: '' },             'チョ': { romaji: 'cho', meaning: '' },
    'ニャ': { romaji: 'nya', meaning: '' },          'ニュ': { romaji: 'nyu', meaning: '' },             'ニョ': { romaji: 'nyo', meaning: '' },
    'ヒャ': { romaji: 'hya', meaning: '' },          'ヒュ': { romaji: 'hyu', meaning: '' },             'ヒョ': { romaji: 'hyo', meaning: '' },
    'ミャ': { romaji: 'mya', meaning: '' },          'ミュ': { romaji: 'myu', meaning: '' },             'ミョ': { romaji: 'myo', meaning: '' },
    'リャ': { romaji: 'rya', meaning: '' },          'リュ': { romaji: 'ryu', meaning: '' },             'リョ': { romaji: 'ryo', meaning: '' },
    'ギャ': { romaji: 'gya', meaning: '' },          'ギュ': { romaji: 'gyu', meaning: '' },             'ギョ': { romaji: 'gyo', meaning: '' },
    'ジャ': { romaji: 'ja', meaning: '' },           'ジュ': { romaji: 'ju', meaning: '' },              'ジョ': { romaji: 'jo', meaning: '' },
    'ビャ': { romaji: 'bya', meaning: '' },          'ビュ': { romaji: 'byu', meaning: '' },             'ビョ': { romaji: 'byo', meaning: '' },
    'ピャ': { romaji: 'pya', meaning: '' },          'ピュ': { romaji: 'pyu', meaning: '' },             'ピョ': { romaji: 'pyo', meaning: '' },
    
    // Extended katakana for foreign words
    'ヴ': { romaji: 'vu', meaning: '' },
    'ティ': { romaji: 'ti', meaning: '' },           'ディ': { romaji: 'di', meaning: '' },              'トゥ': { romaji: 'tu', meaning: '' },
    'ドゥ': { romaji: 'du', meaning: '' },           'ファ': { romaji: 'fa', meaning: '' },              'フィ': { romaji: 'fi', meaning: '' },
    'フェ': { romaji: 'fe', meaning: '' },           'フォ': { romaji: 'fo', meaning: '' },              'ウィ': { romaji: 'wi', meaning: '' },
    'ウェ': { romaji: 'we', meaning: '' },           'ウォ': { romaji: 'wo', meaning: '' },              'ツァ': { romaji: 'tsa', meaning: '' },
    'ツィ': { romaji: 'tsi', meaning: '' },          'ツェ': { romaji: 'tse', meaning: '' },             'ツォ': { romaji: 'tso', meaning: '' },
    'チェ': { romaji: 'che', meaning: '' },          'シェ': { romaji: 'she', meaning: '' },             'ジェ': { romaji: 'je', meaning: '' },
    'イェ': { romaji: 'ye', meaning: '' }
};

// Katakana word data (mainly foreign loanwords)
const katakanaWordData = {
    easy: {
        'アメ': { romaji: 'ame', meaning: 'candy' },
        'イス': { romaji: 'isu', meaning: 'chair' },
        'ウシ': { romaji: 'ushi', meaning: 'cow' },
        'エビ': { romaji: 'ebi', meaning: 'shrimp' },
        'オニ': { romaji: 'oni', meaning: 'demon' },
        'カメ': { romaji: 'kame', meaning: 'turtle' },
        'キツネ': { romaji: 'kitsune', meaning: 'fox' },
        'クマ': { romaji: 'kuma', meaning: 'bear' },
        'ケーキ': { romaji: 'keeki', meaning: 'cake' },
        'コーヒー': { romaji: 'koohii', meaning: 'coffee' },
        'サル': { romaji: 'saru', meaning: 'monkey' },
        'タコ': { romaji: 'tako', meaning: 'octopus' },
        'ナイフ': { romaji: 'naifu', meaning: 'knife' },
        'ハム': { romaji: 'hamu', meaning: 'ham' },
        'マウス': { romaji: 'mausu', meaning: 'mouse' },
        'ヤギ': { romaji: 'yagi', meaning: 'goat' },
        'ライオン': { romaji: 'raion', meaning: 'lion' },
        'ワイン': { romaji: 'wain', meaning: 'wine' },
        // Common foreign words
        'パン': { romaji: 'pan', meaning: 'bread' },
        'ペン': { romaji: 'pen', meaning: 'pen' },
        'ノート': { romaji: 'nooto', meaning: 'notebook' },
        'テスト': { romaji: 'tesuto', meaning: 'test' },
        'ドア': { romaji: 'doa', meaning: 'door' },
        'ベッド': { romaji: 'beddo', meaning: 'bed' },
        'テーブル': { romaji: 'teeburu', meaning: 'table' },
        'バス': { romaji: 'basu', meaning: 'bus' },
        'タクシー': { romaji: 'takushii', meaning: 'taxi' },
        'ホテル': { romaji: 'hoteru', meaning: 'hotel' },
        'レストラン': { romaji: 'resutoran', meaning: 'restaurant' },
        'カフェ': { romaji: 'kafe', meaning: 'cafe' },
        'スーパー': { romaji: 'suupaa', meaning: 'supermarket' },
        'デパート': { romaji: 'depaato', meaning: 'department store' },
        'アイス': { romaji: 'aisu', meaning: 'ice cream' },
        'ジュース': { romaji: 'juusu', meaning: 'juice' },
        'ミルク': { romaji: 'miruku', meaning: 'milk' },
        'バター': { romaji: 'bataa', meaning: 'butter' },
        'チーズ': { romaji: 'chiizu', meaning: 'cheese' },
        'サラダ': { romaji: 'sarada', meaning: 'salad' }
    },
    normal: {
        'アメリカ': { romaji: 'amerika', meaning: 'America' },
        'イギリス': { romaji: 'igirisu', meaning: 'England' },
        'ドイツ': { romaji: 'doitsu', meaning: 'Germany' },
        'フランス': { romaji: 'furansu', meaning: 'France' },
        'イタリア': { romaji: 'itaria', meaning: 'Italy' },
        'ロシア': { romaji: 'roshia', meaning: 'Russia' },
        'カナダ': { romaji: 'kanada', meaning: 'Canada' },
        'オーストラリア': { romaji: 'oosutoraria', meaning: 'Australia' },
        'コンピューター': { romaji: 'konpyuutaa', meaning: 'computer' },
        'インターネット': { romaji: 'intaanetto', meaning: 'internet' },
        'スマートフォン': { romaji: 'sumaatofon', meaning: 'smartphone' },
        'テレビ': { romaji: 'terebi', meaning: 'television' },
        'ラジオ': { romaji: 'rajio', meaning: 'radio' },
        'カメラ': { romaji: 'kamera', meaning: 'camera' },
        'エレベーター': { romaji: 'erebeetaa', meaning: 'elevator' },
        'エスカレーター': { romaji: 'esukareetaa', meaning: 'escalator' },
        'プレゼント': { romaji: 'purezento', meaning: 'present' },
        'パーティー': { romaji: 'paatii', meaning: 'party' },
        'ピクニック': { romaji: 'pikunikku', meaning: 'picnic' },
        'コンサート': { romaji: 'konsaato', meaning: 'concert' },
        'スポーツ': { romaji: 'supootsu', meaning: 'sports' },
        'サッカー': { romaji: 'sakkaa', meaning: 'soccer' },
        'バスケットボール': { romaji: 'basukettoboru', meaning: 'basketball' },
        'テニス': { romaji: 'tenisu', meaning: 'tennis' },
        'ゴルフ': { romaji: 'gorufu', meaning: 'golf' },
        'スキー': { romaji: 'sukii', meaning: 'skiing' },
        'ダンス': { romaji: 'dansu', meaning: 'dance' },
        'ミュージック': { romaji: 'myuujikku', meaning: 'music' },
        'クラシック': { romaji: 'kurashikku', meaning: 'classical' },
        'ジャズ': { romaji: 'jazu', meaning: 'jazz' },
        'ロック': { romaji: 'rokku', meaning: 'rock' },
        'ポップ': { romaji: 'poppu', meaning: 'pop' },
        'ファッション': { romaji: 'fasshon', meaning: 'fashion' },
        'ドレス': { romaji: 'doresu', meaning: 'dress' },
        'スーツ': { romaji: 'suutsu', meaning: 'suit' },
        'ジーンズ': { romaji: 'jiinzu', meaning: 'jeans' },
        'セーター': { romaji: 'seetaa', meaning: 'sweater' },
        'ジャケット': { romaji: 'jaketto', meaning: 'jacket' },
        'スニーカー': { romaji: 'suniikaa', meaning: 'sneakers' },
        'ブーツ': { romaji: 'buutsu', meaning: 'boots' }
    },
    hard: {
        'アルバイト': { romaji: 'arubaito', meaning: 'part-time job' },
        'インフルエンザ': { romaji: 'infuruenza', meaning: 'influenza' },
        'エネルギー': { romaji: 'enerugii', meaning: 'energy' },
        'オーケストラ': { romaji: 'ookesutora', meaning: 'orchestra' },
        'カリキュラム': { romaji: 'karikyuramu', meaning: 'curriculum' },
        'キャンペーン': { romaji: 'kyanpeen', meaning: 'campaign' },
        'クリスマス': { romaji: 'kurisumasu', meaning: 'Christmas' },
        'グローバル': { romaji: 'guroobaru', meaning: 'global' },
        'ケーブル': { romaji: 'keeburu', meaning: 'cable' },
        'コミュニケーション': { romaji: 'komyunikeeshon', meaning: 'communication' },
        'サンドイッチ': { romaji: 'sandoitchi', meaning: 'sandwich' },
        'シミュレーション': { romaji: 'shimyureeshon', meaning: 'simulation' },
        'スケジュール': { romaji: 'sukejuuru', meaning: 'schedule' },
        'ストレス': { romaji: 'sutoresu', meaning: 'stress' },
        'セキュリティ': { romaji: 'sekyuriti', meaning: 'security' },
        'ソフトウェア': { romaji: 'sofutowea', meaning: 'software' },
        'ターミナル': { romaji: 'taaminaru', meaning: 'terminal' },
        'チャレンジ': { romaji: 'charenji', meaning: 'challenge' },
        'データベース': { romaji: 'deetabeesu', meaning: 'database' },
        'ナビゲーション': { romaji: 'nabigeshon', meaning: 'navigation' },
        'ハンバーガー': { romaji: 'hanbaagaa', meaning: 'hamburger' },
        'ビジネス': { romaji: 'bijinesu', meaning: 'business' },
        'プロジェクト': { romaji: 'purojekuto', meaning: 'project' },
        'プログラム': { romaji: 'puroguramu', meaning: 'program' },
        'ヘリコプター': { romaji: 'herikoputaa', meaning: 'helicopter' },
        'ボランティア': { romaji: 'borantia', meaning: 'volunteer' },
        'マネージメント': { romaji: 'manējimento', meaning: 'management' },
        'ミーティング': { romaji: 'miitingu', meaning: 'meeting' },
        'メッセージ': { romaji: 'messēji', meaning: 'message' },
        'モニター': { romaji: 'monitaa', meaning: 'monitor' },
        'ユーザー': { romaji: 'yuuzaa', meaning: 'user' },
        'ラウンジ': { romaji: 'raunji', meaning: 'lounge' },
        'リサーチ': { romaji: 'risaachi', meaning: 'research' },
        'ルーティン': { romaji: 'ruutin', meaning: 'routine' },
        'レストラン': { romaji: 'resutoran', meaning: 'restaurant' },
        'ロビー': { romaji: 'robii', meaning: 'lobby' },
        'ワークショップ': { romaji: 'waakushoppu', meaning: 'workshop' }
    }
};

// Enhanced kanji data with readings and meanings
// Kanji data with romaji pronunciation and meanings
const kanjiData = {
    // Basic numbers
    '一': { romaji: 'ichi', meaning: 'one' },
    '二': { romaji: 'ni', meaning: 'two' },
    '三': { romaji: 'san', meaning: 'three' },
    '四': { romaji: 'shi', meaning: 'four' },
    '五': { romaji: 'go', meaning: 'five' },
    '六': { romaji: 'roku', meaning: 'six' },
    '七': { romaji: 'shichi', meaning: 'seven' },
    '八': { romaji: 'hachi', meaning: 'eight' },
    '九': { romaji: 'kyuu', meaning: 'nine' },
    '十': { romaji: 'juu', meaning: 'ten' },
    '百': { romaji: 'hyaku', meaning: 'hundred' },
    '千': { romaji: 'sen', meaning: 'thousand' },
    '万': { romaji: 'man', meaning: 'ten thousand' },
    
    // Time and calendar
    '日': { romaji: 'hi', meaning: 'day/sun' },
    '月': { romaji: 'tsuki', meaning: 'month/moon' },
    '年': { romaji: 'toshi', meaning: 'year' },
    '時': { romaji: 'toki', meaning: 'time' },
    '週': { romaji: 'shuu', meaning: 'week' },
    '今': { romaji: 'ima', meaning: 'now' },
    '前': { romaji: 'mae', meaning: 'before' },
    '後': { romaji: 'ato', meaning: 'after' },
    '毎': { romaji: 'mai', meaning: 'every' },
    
    // People and family
    '人': { romaji: 'hito', meaning: 'person' },
    '子': { romaji: 'ko', meaning: 'child' },
    '女': { romaji: 'onna', meaning: 'woman' },
    '男': { romaji: 'otoko', meaning: 'man' },
    '父': { romaji: 'chichi', meaning: 'father' },
    '母': { romaji: 'haha', meaning: 'mother' },
    '兄': { romaji: 'ani', meaning: 'older brother' },
    '弟': { romaji: 'otouto', meaning: 'younger brother' },
    '姉': { romaji: 'ane', meaning: 'older sister' },
    '妹': { romaji: 'imouto', meaning: 'younger sister' },
    '友': { romaji: 'tomo', meaning: 'friend' },
    '先': { romaji: 'saki', meaning: 'ahead/prior' },
    '生': { romaji: 'sei', meaning: 'life/birth' },
    
    // Body parts
    '手': { romaji: 'te', meaning: 'hand' },
    '足': { romaji: 'ashi', meaning: 'foot/leg' },
    '目': { romaji: 'me', meaning: 'eye' },
    '耳': { romaji: 'mimi', meaning: 'ear' },
    '口': { romaji: 'kuchi', meaning: 'mouth' },
    '鼻': { romaji: 'hana', meaning: 'nose' },
    '頭': { romaji: 'atama', meaning: 'head' },
    '心': { romaji: 'kokoro', meaning: 'heart/mind' },
    '体': { romaji: 'karada', meaning: 'body' },
    
    // Nature
    '山': { romaji: 'yama', meaning: 'mountain' },
    '川': { romaji: 'kawa', meaning: 'river' },
    '海': { romaji: 'umi', meaning: 'sea' },
    '空': { romaji: 'sora', meaning: 'sky' },
    '雲': { romaji: 'kumo', meaning: 'cloud' },
    '雨': { romaji: 'ame', meaning: 'rain' },
    '雪': { romaji: 'yuki', meaning: 'snow' },
    '風': { romaji: 'kaze', meaning: 'wind' },
    '火': { romaji: 'hi', meaning: 'fire' },
    '水': { romaji: 'mizu', meaning: 'water' },
    '土': { romaji: 'tsuchi', meaning: 'earth/soil' },
    '木': { romaji: 'ki', meaning: 'tree/wood' },
    '花': { romaji: 'hana', meaning: 'flower' },
    '草': { romaji: 'kusa', meaning: 'grass' },
    '石': { romaji: 'ishi', meaning: 'stone' },
    
    // Animals
    '犬': { romaji: 'inu', meaning: 'dog' },
    '猫': { romaji: 'neko', meaning: 'cat' },
    '鳥': { romaji: 'tori', meaning: 'bird' },
    '魚': { romaji: 'sakana', meaning: 'fish' },
    '馬': { romaji: 'uma', meaning: 'horse' },
    '牛': { romaji: 'ushi', meaning: 'cow' },
    '虫': { romaji: 'mushi', meaning: 'insect' },
    
    // Places and buildings
    '家': { romaji: 'ie', meaning: 'house' },
    '国': { romaji: 'kuni', meaning: 'country' },
    '町': { romaji: 'machi', meaning: 'town' },
    '村': { romaji: 'mura', meaning: 'village' },
    '市': { romaji: 'shi', meaning: 'city' },
    '学': { romaji: 'gaku', meaning: 'learn' },
    '校': { romaji: 'kou', meaning: 'school' },
    '店': { romaji: 'mise', meaning: 'store' },
    '駅': { romaji: 'eki', meaning: 'station' },
    '病': { romaji: 'byou', meaning: 'illness' },
    '院': { romaji: 'in', meaning: 'institution' },
    '車': { romaji: 'kuruma', meaning: 'car' },
    '道': { romaji: 'michi', meaning: 'road/way' },
    '門': { romaji: 'mon', meaning: 'gate' },
    '橋': { romaji: 'hashi', meaning: 'bridge' },
    
    // Actions and verbs
    '行': { romaji: 'iku', meaning: 'go' },
    '来': { romaji: 'kuru', meaning: 'come' },
    '帰': { romaji: 'kaeru', meaning: 'return' },
    '見': { romaji: 'miru', meaning: 'see' },
    '聞': { romaji: 'kiku', meaning: 'hear' },
    '読': { romaji: 'yomu', meaning: 'read' },
    '書': { romaji: 'kaku', meaning: 'write' },
    '話': { romaji: 'hanasu', meaning: 'speak' },
    '食': { romaji: 'taberu', meaning: 'eat' },
    '飲': { romaji: 'nomu', meaning: 'drink' },
    '買': { romaji: 'kau', meaning: 'buy' },
    '売': { romaji: 'uru', meaning: 'sell' },
    '作': { romaji: 'tsukuru', meaning: 'make' },
    '立': { romaji: 'tatsu', meaning: 'stand' },
    '座': { romaji: 'suwaru', meaning: 'sit' },
    '走': { romaji: 'hashiru', meaning: 'run' },
    '歩': { romaji: 'aruku', meaning: 'walk' },
    '止': { romaji: 'tomaru', meaning: 'stop' },
    '休': { romaji: 'yasumu', meaning: 'rest' },
    '働': { romaji: 'hataraku', meaning: 'work' },
    '勉': { romaji: 'ben', meaning: 'diligence' },
    '強': { romaji: 'tsuyoi', meaning: 'strong' },
    '教': { romaji: 'oshieru', meaning: 'teach' },
    '習': { romaji: 'narau', meaning: 'learn' },
    '思': { romaji: 'omou', meaning: 'think' },
    '考': { romaji: 'kangaeru', meaning: 'consider' },
    '知': { romaji: 'shiru', meaning: 'know' },
    '分': { romaji: 'wakaru', meaning: 'divide/understand' },
    '出': { romaji: 'deru', meaning: 'exit' },
    '入': { romaji: 'hairu', meaning: 'enter' },
    '上': { romaji: 'ue', meaning: 'above' },
    '下': { romaji: 'shita', meaning: 'below' },
    '中': { romaji: 'naka', meaning: 'inside' },
    '外': { romaji: 'soto', meaning: 'outside' },
    '右': { romaji: 'migi', meaning: 'right' },
    '左': { romaji: 'hidari', meaning: 'left' },
    '北': { romaji: 'kita', meaning: 'north' },
    '南': { romaji: 'minami', meaning: 'south' },
    '東': { romaji: 'higashi', meaning: 'east' },
    '西': { romaji: 'nishi', meaning: 'west' },
    
    // Adjectives and descriptions
    '大': { romaji: 'ookii', meaning: 'big' },
    '小': { romaji: 'chiisai', meaning: 'small' },
    '高': { romaji: 'takai', meaning: 'high/tall' },
    '低': { romaji: 'hikui', meaning: 'low' },
    '長': { romaji: 'nagai', meaning: 'long' },
    '短': { romaji: 'mijikai', meaning: 'short' },
    '新': { romaji: 'atarashii', meaning: 'new' },
    '古': { romaji: 'furui', meaning: 'old' },
    '若': { romaji: 'wakai', meaning: 'young' },
    '多': { romaji: 'ooi', meaning: 'many' },
    '少': { romaji: 'sukunai', meaning: 'few' },
    '早': { romaji: 'hayai', meaning: 'early' },
    '遅': { romaji: 'osoi', meaning: 'late' },
    '近': { romaji: 'chikai', meaning: 'near' },
    '遠': { romaji: 'tooi', meaning: 'far' },
    '明': { romaji: 'akarui', meaning: 'bright' },
    '暗': { romaji: 'kurai', meaning: 'dark' },
    '白': { romaji: 'shiro', meaning: 'white' },
    '黒': { romaji: 'kuro', meaning: 'black' },
    '赤': { romaji: 'aka', meaning: 'red' },
    '青': { romaji: 'ao', meaning: 'blue' },
    '黄': { romaji: 'ki', meaning: 'yellow' },
    '緑': { romaji: 'midori', meaning: 'green' },
    
    // Objects and things
    '本': { romaji: 'hon', meaning: 'book' },
    '紙': { romaji: 'kami', meaning: 'paper' },
    '字': { romaji: 'ji', meaning: 'character' },
    '文': { romaji: 'bun', meaning: 'sentence' },
    '名': { romaji: 'namae', meaning: 'name' },
    '音': { romaji: 'oto', meaning: 'sound' },
    '声': { romaji: 'koe', meaning: 'voice' },
    '言': { romaji: 'iu', meaning: 'say' },
    '語': { romaji: 'go', meaning: 'language' },
    '電': { romaji: 'den', meaning: 'electricity' },
    '気': { romaji: 'ki', meaning: 'spirit/energy' },
    '物': { romaji: 'mono', meaning: 'thing' },
    '品': { romaji: 'shina', meaning: 'goods' },
    '用': { romaji: 'you', meaning: 'use' },
    '方': { romaji: 'kata', meaning: 'direction/way' },
    '間': { romaji: 'aida', meaning: 'interval' },
    '所': { romaji: 'tokoro', meaning: 'place' },
    '場': { romaji: 'ba', meaning: 'place' },
    '力': { romaji: 'chikara', meaning: 'power' },
    '元': { romaji: 'moto', meaning: 'origin' },
    '金': { romaji: 'kin', meaning: 'gold/money' },
    '銀': { romaji: 'gin', meaning: 'silver' },
    '玉': { romaji: 'tama', meaning: 'ball/gem' },
    '宝': { romaji: 'takara', meaning: 'treasure' },
    '服': { romaji: 'fuku', meaning: 'clothes' },
    '靴': { romaji: 'kutsu', meaning: 'shoes' },
    '帽': { romaji: 'bou', meaning: 'hat' },
    '袋': { romaji: 'fukuro', meaning: 'bag' },
    '箱': { romaji: 'hako', meaning: 'box' },
    '机': { romaji: 'tsukue', meaning: 'desk' },
    '椅': { romaji: 'isu', meaning: 'chair' },
    '窓': { romaji: 'mado', meaning: 'window' },
    '戸': { romaji: 'to', meaning: 'door' },
    '鍵': { romaji: 'kagi', meaning: 'key' },
    '刀': { romaji: 'katana', meaning: 'sword' },
    '弓': { romaji: 'yumi', meaning: 'bow' },
    '矢': { romaji: 'ya', meaning: 'arrow' },
    '船': { romaji: 'fune', meaning: 'ship' },
    '飛': { romaji: 'tobu', meaning: 'fly' },
    '歌': { romaji: 'uta', meaning: 'song' },
    '画': { romaji: 'ga', meaning: 'picture' },
    '絵': { romaji: 'e', meaning: 'picture' },
    '写': { romaji: 'utsusu', meaning: 'copy' },
    '真': { romaji: 'shin', meaning: 'true' }
};

// Multi-character kanji words dataset
const kanjiWordData = {
    easy: {
        // Basic family and people
        '父母': { romaji: 'fubo', meaning: 'parents' },
        '兄弟': { romaji: 'kyoudai', meaning: 'brothers/siblings' },
        '姉妹': { romaji: 'shimai', meaning: 'sisters' },
        '子供': { romaji: 'kodomo', meaning: 'child/children' },
        '友人': { romaji: 'yuujin', meaning: 'friend' },
        '先生': { romaji: 'sensei', meaning: 'teacher' },
        '学生': { romaji: 'gakusei', meaning: 'student' },
        
        // Basic time expressions
        '今日': { romaji: 'kyou', meaning: 'today' },
        '毎日': { romaji: 'mainichi', meaning: 'every day' },
        '一日': { romaji: 'ichinichi', meaning: 'one day' },
        '三日': { romaji: 'mikka', meaning: 'three days/3rd day' },
        '今年': { romaji: 'kotoshi', meaning: 'this year' },
        '来年': { romaji: 'rainen', meaning: 'next year' },
        
        // Basic places
        '学校': { romaji: 'gakkou', meaning: 'school' },
        '家族': { romaji: 'kazoku', meaning: 'family' },
        '自分': { romaji: 'jibun', meaning: 'oneself' },
        '人生': { romaji: 'jinsei', meaning: 'life' },
        
        // Basic actions
        '勉強': { romaji: 'benkyou', meaning: 'study' },
        '食事': { romaji: 'shokuji', meaning: 'meal' },
        '買物': { romaji: 'kaimono', meaning: 'shopping' },
        '読書': { romaji: 'dokusho', meaning: 'reading' },
        '休日': { romaji: 'kyuujitsu', meaning: 'holiday' },
        
        // Basic nature
        '大空': { romaji: 'oozora', meaning: 'big sky' },
        '青空': { romaji: 'aozora', meaning: 'blue sky' },
        '花火': { romaji: 'hanabi', meaning: 'fireworks' },
        '雪山': { romaji: 'yukiyama', meaning: 'snow mountain' },
        
        // Basic objects
        '本屋': { romaji: 'honya', meaning: 'bookstore' },
        '手紙': { romaji: 'tegami', meaning: 'letter' },
        '名前': { romaji: 'namae', meaning: 'name' },
        '電話': { romaji: 'denwa', meaning: 'telephone' },
        '電気': { romaji: 'denki', meaning: 'electricity/light' }
    },
    
    normal: {
        // Time and calendar
        '今月': { romaji: 'kongetsu', meaning: 'this month' },
        '来月': { romaji: 'raigetsu', meaning: 'next month' },
        '先月': { romaji: 'sengetsu', meaning: 'last month' },
        '今週': { romaji: 'konshuu', meaning: 'this week' },
        '来週': { romaji: 'raishuu', meaning: 'next week' },
        '先週': { romaji: 'senshuu', meaning: 'last week' },
        '毎週': { romaji: 'maishuu', meaning: 'every week' },
        '毎月': { romaji: 'maitsuki', meaning: 'every month' },
        '毎年': { romaji: 'maitoshi', meaning: 'every year' },
        '時間': { romaji: 'jikan', meaning: 'time' },
        '午前': { romaji: 'gozen', meaning: 'morning/AM' },
        '午後': { romaji: 'gogo', meaning: 'afternoon/PM' },
        
        // Places and locations
        '病院': { romaji: 'byouin', meaning: 'hospital' },
        '図書': { romaji: 'tosho', meaning: 'library books' },
        '大学': { romaji: 'daigaku', meaning: 'university' },
        '小学': { romaji: 'shougaku', meaning: 'elementary school' },
        '中学': { romaji: 'chuugaku', meaning: 'middle school' },
        '高校': { romaji: 'koukou', meaning: 'high school' },
        '市場': { romaji: 'ichiba', meaning: 'market' },
        '工場': { romaji: 'koujou', meaning: 'factory' },
        '空港': { romaji: 'kuukou', meaning: 'airport' },
        '銀行': { romaji: 'ginkou', meaning: 'bank' },
        '神社': { romaji: 'jinja', meaning: 'shrine' },
        
        // Actions and activities
        '教育': { romaji: 'kyouiku', meaning: 'education' },
        '練習': { romaji: 'renshuu', meaning: 'practice' },
        '習字': { romaji: 'shuuji', meaning: 'calligraphy' },
        '工作': { romaji: 'kousaku', meaning: 'handicraft' },
        '作品': { romaji: 'sakuhin', meaning: 'work of art' },
        '運動': { romaji: 'undou', meaning: 'exercise' },
        '散歩': { romaji: 'sanpo', meaning: 'walk' },
        '旅行': { romaji: 'ryokou', meaning: 'travel' },
        '仕事': { romaji: 'shigoto', meaning: 'work/job' },
        
        // Nature and weather
        '天気': { romaji: 'tenki', meaning: 'weather' },
        '台風': { romaji: 'taifuu', meaning: 'typhoon' },
        '地震': { romaji: 'jishin', meaning: 'earthquake' },
        '自然': { romaji: 'shizen', meaning: 'nature' },
        '森林': { romaji: 'shinrin', meaning: 'forest' },
        '海岸': { romaji: 'kaigan', meaning: 'seashore' },
        '湖水': { romaji: 'kosui', meaning: 'lake water' },
        '春風': { romaji: 'harukaze', meaning: 'spring breeze' },
        
        // Transportation
        '電車': { romaji: 'densha', meaning: 'train' },
        '自動': { romaji: 'jidou', meaning: 'automatic' },
        '交通': { romaji: 'koutsuu', meaning: 'traffic' },
        '道路': { romaji: 'douro', meaning: 'road' },
        '歩道': { romaji: 'hodou', meaning: 'sidewalk' },
        '横断': { romaji: 'oudan', meaning: 'crossing' },
        
        // Daily life
        '生活': { romaji: 'seikatsu', meaning: 'daily life' },
        '料理': { romaji: 'ryouri', meaning: 'cooking' },
        '掃除': { romaji: 'souji', meaning: 'cleaning' },
        '洗濯': { romaji: 'sentaku', meaning: 'laundry' },
        '買い物': { romaji: 'kaimono', meaning: 'shopping' },
        '家事': { romaji: 'kaji', meaning: 'housework' },
        '健康': { romaji: 'kenkou', meaning: 'health' },
        
        // Objects and tools
        '道具': { romaji: 'dougu', meaning: 'tool' },
        '家具': { romaji: 'kagu', meaning: 'furniture' },
        '食器': { romaji: 'shokki', meaning: 'tableware' },
        '台所': { romaji: 'daidokoro', meaning: 'kitchen' },
        '玄関': { romaji: 'genkan', meaning: 'entrance' },
        '寝室': { romaji: 'shinshitsu', meaning: 'bedroom' },
        '居間': { romaji: 'ima', meaning: 'living room' },
        '風呂': { romaji: 'furo', meaning: 'bath' },
        '庭園': { romaji: 'teien', meaning: 'garden' }
    },
    
    hard: {
        // Complex time expressions
        '昨日': { romaji: 'kinou', meaning: 'yesterday' },
        '明日': { romaji: 'ashita', meaning: 'tomorrow' },
        '一昨日': { romaji: 'ototoi', meaning: 'day before yesterday' },
        '明後日': { romaji: 'asatte', meaning: 'day after tomorrow' },
        '過去': { romaji: 'kako', meaning: 'past' },
        '現在': { romaji: 'genzai', meaning: 'present' },
        '未来': { romaji: 'mirai', meaning: 'future' },
        '永遠': { romaji: 'eien', meaning: 'eternity' },
        '瞬間': { romaji: 'shunkan', meaning: 'moment' },
        
        // Abstract concepts
        '自由': { romaji: 'jiyuu', meaning: 'freedom' },
        '平和': { romaji: 'heiwa', meaning: 'peace' },
        '真実': { romaji: 'shinjitsu', meaning: 'truth' },
        '正義': { romaji: 'seigi', meaning: 'justice' },
        '希望': { romaji: 'kibou', meaning: 'hope' },
        '愛情': { romaji: 'aijou', meaning: 'love' },
        '友情': { romaji: 'yuujou', meaning: 'friendship' },
        '信頼': { romaji: 'shinrai', meaning: 'trust' },
        '責任': { romaji: 'sekinin', meaning: 'responsibility' },
        '努力': { romaji: 'doryoku', meaning: 'effort' },
        '成功': { romaji: 'seikou', meaning: 'success' },
        '失敗': { romaji: 'shippai', meaning: 'failure' },
        '経験': { romaji: 'keiken', meaning: 'experience' },
        '知識': { romaji: 'chishiki', meaning: 'knowledge' },
        '技術': { romaji: 'gijutsu', meaning: 'technology' },
        '文化': { romaji: 'bunka', meaning: 'culture' },
        '芸術': { romaji: 'geijutsu', meaning: 'art' },
        '音楽': { romaji: 'ongaku', meaning: 'music' },
        '文学': { romaji: 'bungaku', meaning: 'literature' },
        '歴史': { romaji: 'rekishi', meaning: 'history' },
        '科学': { romaji: 'kagaku', meaning: 'science' },
        '数学': { romaji: 'suugaku', meaning: 'mathematics' },
        '物理': { romaji: 'butsuri', meaning: 'physics' },
        '化学': { romaji: 'kagaku', meaning: 'chemistry' },
        '生物': { romaji: 'seibutsu', meaning: 'biology' },
        '地理': { romaji: 'chiri', meaning: 'geography' },
        '哲学': { romaji: 'tetsugaku', meaning: 'philosophy' },
        '心理': { romaji: 'shinri', meaning: 'psychology' },
        '社会': { romaji: 'shakai', meaning: 'society' },
        '経済': { romaji: 'keizai', meaning: 'economy' },
        '政治': { romaji: 'seiji', meaning: 'politics' },
        '法律': { romaji: 'houritsu', meaning: 'law' },
        '宗教': { romaji: 'shuukyou', meaning: 'religion' },
        
        // Complex places and institutions
        '首都': { romaji: 'shuto', meaning: 'capital city' },
        '都市': { romaji: 'toshi', meaning: 'city' },
        '農村': { romaji: 'nouson', meaning: 'farming village' },
        '工業': { romaji: 'kougyou', meaning: 'industry' },
        '商業': { romaji: 'shougyou', meaning: 'commerce' },
        '企業': { romaji: 'kigyou', meaning: 'enterprise' },
        '会社': { romaji: 'kaisha', meaning: 'company' },
        '組織': { romaji: 'soshiki', meaning: 'organization' },
        '団体': { romaji: 'dantai', meaning: 'group' },
        '機関': { romaji: 'kikan', meaning: 'institution' },
        '施設': { romaji: 'shisetsu', meaning: 'facility' },
        '建物': { romaji: 'tatemono', meaning: 'building' },
        '構造': { romaji: 'kouzou', meaning: 'structure' },
        '設備': { romaji: 'setsubi', meaning: 'equipment' },
        '装置': { romaji: 'souchi', meaning: 'device' },
        '機械': { romaji: 'kikai', meaning: 'machine' },
        '器具': { romaji: 'kigu', meaning: 'instrument' },
        '材料': { romaji: 'zairyou', meaning: 'material' },
        '原料': { romaji: 'genryou', meaning: 'raw material' },
        '製品': { romaji: 'seihin', meaning: 'product' },
        '商品': { romaji: 'shouhin', meaning: 'commodity' },
        '品質': { romaji: 'hinshitsu', meaning: 'quality' },
        '価格': { romaji: 'kakaku', meaning: 'price' },
        '価値': { romaji: 'kachi', meaning: 'value' },
        '利益': { romaji: 'rieki', meaning: 'profit' },
        '損失': { romaji: 'sonshitsu', meaning: 'loss' },
        '投資': { romaji: 'toushi', meaning: 'investment' },
        '預金': { romaji: 'yokin', meaning: 'deposit' },
        '貯金': { romaji: 'chokin', meaning: 'savings' },
        '借金': { romaji: 'shakkin', meaning: 'debt' },
        '税金': { romaji: 'zeikin', meaning: 'tax' },
        '給料': { romaji: 'kyuuryou', meaning: 'salary' },
        '賃金': { romaji: 'chingin', meaning: 'wage' },
        '収入': { romaji: 'shuunyuu', meaning: 'income' },
        '支出': { romaji: 'shishutsu', meaning: 'expenditure' },
        '計算': { romaji: 'keisan', meaning: 'calculation' },
        '統計': { romaji: 'toukei', meaning: 'statistics' },
        '分析': { romaji: 'bunseki', meaning: 'analysis' },
        '研究': { romaji: 'kenkyuu', meaning: 'research' },
        '調査': { romaji: 'chousa', meaning: 'investigation' },
        '実験': { romaji: 'jikken', meaning: 'experiment' },
        '観察': { romaji: 'kansatsu', meaning: 'observation' },
        '発見': { romaji: 'hakken', meaning: 'discovery' },
        '発明': { romaji: 'hatsumei', meaning: 'invention' },
        '創造': { romaji: 'souzou', meaning: 'creation' },
        '想像': { romaji: 'souzou', meaning: 'imagination' },
        '理想': { romaji: 'risou', meaning: 'ideal' },
        '夢想': { romaji: 'musou', meaning: 'dream/fantasy' },
        '空想': { romaji: 'kuusou', meaning: 'daydream' },
        '現実': { romaji: 'genjitsu', meaning: 'reality' },
        '事実': { romaji: 'jijitsu', meaning: 'fact' },
        '真理': { romaji: 'shinri', meaning: 'truth' },
        '理論': { romaji: 'riron', meaning: 'theory' },
        '法則': { romaji: 'housoku', meaning: 'law/rule' },
        '原理': { romaji: 'genri', meaning: 'principle' },
        '基本': { romaji: 'kihon', meaning: 'basics' },
        '基礎': { romaji: 'kiso', meaning: 'foundation' },
        '根本': { romaji: 'konpon', meaning: 'root/basis' },
        '本質': { romaji: 'honshitsu', meaning: 'essence' },
        '性質': { romaji: 'seishitsu', meaning: 'nature/property' },
        '特徴': { romaji: 'tokuchou', meaning: 'characteristic' },
        '特色': { romaji: 'tokushoku', meaning: 'feature' },
        '個性': { romaji: 'kosei', meaning: 'personality' },
        '人格': { romaji: 'jinkaku', meaning: 'character' },
        '性格': { romaji: 'seikaku', meaning: 'personality' },
        '態度': { romaji: 'taido', meaning: 'attitude' },
        '行動': { romaji: 'koudou', meaning: 'behavior' },
        '習慣': { romaji: 'shuukan', meaning: 'habit' },
        '風習': { romaji: 'fuushuu', meaning: 'custom' },
        '伝統': { romaji: 'dentou', meaning: 'tradition' },
        '文明': { romaji: 'bunmei', meaning: 'civilization' },
        '進歩': { romaji: 'shinpo', meaning: 'progress' },
        '発展': { romaji: 'hatten', meaning: 'development' },
        '発達': { romaji: 'hattatsu', meaning: 'development' },
        '成長': { romaji: 'seichou', meaning: 'growth' },
        '向上': { romaji: 'koujou', meaning: 'improvement' },
        '改善': { romaji: 'kaizen', meaning: 'improvement' },
        '改良': { romaji: 'kairyou', meaning: 'improvement' },
        '変化': { romaji: 'henka', meaning: 'change' },
        '変更': { romaji: 'henkou', meaning: 'change' },
        '転換': { romaji: 'tenkan', meaning: 'conversion' },
        '革命': { romaji: 'kakumei', meaning: 'revolution' },
        '改革': { romaji: 'kaikaku', meaning: 'reform' },
        '革新': { romaji: 'kakushin', meaning: 'innovation' },
        '新規': { romaji: 'shinki', meaning: 'new' },
        '最新': { romaji: 'saishin', meaning: 'latest' },
        '最高': { romaji: 'saikou', meaning: 'highest' },
        '最低': { romaji: 'saitei', meaning: 'lowest' },
        '最大': { romaji: 'saidai', meaning: 'maximum' },
        '最小': { romaji: 'saishou', meaning: 'minimum' },
        '最良': { romaji: 'sairyou', meaning: 'best' },
        '最悪': { romaji: 'saiaku', meaning: 'worst' },
        '優秀': { romaji: 'yuushuu', meaning: 'excellent' },
        '完全': { romaji: 'kanzen', meaning: 'perfect' },
        '完成': { romaji: 'kansei', meaning: 'completion' },
        '終了': { romaji: 'shuuryou', meaning: 'end' },
        '開始': { romaji: 'kaishi', meaning: 'beginning' },
        '始まり': { romaji: 'hajimari', meaning: 'beginning' },
        '終わり': { romaji: 'owari', meaning: 'end' },
        '継続': { romaji: 'keizoku', meaning: 'continuation' },
        '中断': { romaji: 'chuudan', meaning: 'interruption' },
        '停止': { romaji: 'teishi', meaning: 'stop' },
        '中止': { romaji: 'chuushi', meaning: 'cancellation' },
        '禁止': { romaji: 'kinshi', meaning: 'prohibition' },
        '許可': { romaji: 'kyoka', meaning: 'permission' },
        '承認': { romaji: 'shounin', meaning: 'approval' },
        '拒否': { romaji: 'kyohi', meaning: 'refusal' },
        '反対': { romaji: 'hantai', meaning: 'opposition' },
        '賛成': { romaji: 'sansei', meaning: 'agreement' },
        '同意': { romaji: 'doui', meaning: 'consent' },
        '合意': { romaji: 'goui', meaning: 'agreement' },
        '契約': { romaji: 'keiyaku', meaning: 'contract' },
        '約束': { romaji: 'yakusoku', meaning: 'promise' },
        '保証': { romaji: 'hoshou', meaning: 'guarantee' },
        '確認': { romaji: 'kakunin', meaning: 'confirmation' },
        '確実': { romaji: 'kakujitsu', meaning: 'certainty' },
        '正確': { romaji: 'seikaku', meaning: 'accuracy' },
        '厳密': { romaji: 'genmitsu', meaning: 'strict' },
        '詳細': { romaji: 'shousai', meaning: 'detail' },
        '簡単': { romaji: 'kantan', meaning: 'simple' },
        '複雑': { romaji: 'fukuzatsu', meaning: 'complex' },
        '困難': { romaji: 'konnan', meaning: 'difficulty' },
        '容易': { romaji: 'youi', meaning: 'easy' },
        '便利': { romaji: 'benri', meaning: 'convenient' },
        '不便': { romaji: 'fuben', meaning: 'inconvenient' },
        '安全': { romaji: 'anzen', meaning: 'safety' },
        '危険': { romaji: 'kiken', meaning: 'danger' },
        '安心': { romaji: 'anshin', meaning: 'peace of mind' },
        '心配': { romaji: 'shinpai', meaning: 'worry' },
        '不安': { romaji: 'fuan', meaning: 'anxiety' },
        '恐怖': { romaji: 'kyoufu', meaning: 'fear' },
        '勇気': { romaji: 'yuuki', meaning: 'courage' },
        '決心': { romaji: 'kesshin', meaning: 'determination' },
        '意志': { romaji: 'ishi', meaning: 'will' },
        '意図': { romaji: 'ito', meaning: 'intention' },
        '目的': { romaji: 'mokuteki', meaning: 'purpose' },
        '計画': { romaji: 'keikaku', meaning: 'plan' },
        '準備': { romaji: 'junbi', meaning: 'preparation' },
        '用意': { romaji: 'youi', meaning: 'preparation' },
        '支度': { romaji: 'shitaku', meaning: 'preparation' },
        '整理': { romaji: 'seiri', meaning: 'organization' },
        '整頓': { romaji: 'seiton', meaning: 'arrangement' },
        '管理': { romaji: 'kanri', meaning: 'management' },
        '運営': { romaji: 'un-ei', meaning: 'management' },
        '経営': { romaji: 'keiei', meaning: 'management' },
        '指導': { romaji: 'shidou', meaning: 'guidance' },
        '指示': { romaji: 'shiji', meaning: 'instruction' },
        '命令': { romaji: 'meirei', meaning: 'order' },
        '要求': { romaji: 'youkyuu', meaning: 'demand' },
        '依頼': { romaji: 'irai', meaning: 'request' },
        '申請': { romaji: 'shinsei', meaning: 'application' },
        '届出': { romaji: 'todokede', meaning: 'notification' },
        '報告': { romaji: 'houkoku', meaning: 'report' },
        '連絡': { romaji: 'renraku', meaning: 'contact' },
        '通知': { romaji: 'tsuchi', meaning: 'notice' },
        '発表': { romaji: 'happyou', meaning: 'announcement' },
        '宣言': { romaji: 'sengen', meaning: 'declaration' },
        '説明': { romaji: 'setsumei', meaning: 'explanation' },
        '解説': { romaji: 'kaisetsu', meaning: 'commentary' },
        '講義': { romaji: 'kougi', meaning: 'lecture' },
        '講演': { romaji: 'kouen', meaning: 'lecture' },
        '演説': { romaji: 'enzetsu', meaning: 'speech' },
        '発言': { romaji: 'hatsugen', meaning: 'statement' },
        '意見': { romaji: 'iken', meaning: 'opinion' },
        '提案': { romaji: 'teian', meaning: 'proposal' },
        '提出': { romaji: 'teishutsu', meaning: 'submission' },
        '提供': { romaji: 'teikyou', meaning: 'provision' },
        '供給': { romaji: 'kyoukyuu', meaning: 'supply' },
        '配給': { romaji: 'haikyuu', meaning: 'distribution' },
        '配達': { romaji: 'haitatsu', meaning: 'delivery' },
        '輸送': { romaji: 'yusou', meaning: 'transport' },
        '運搬': { romaji: 'unpan', meaning: 'transport' },
        '移動': { romaji: 'idou', meaning: 'movement' },
        '移転': { romaji: 'iten', meaning: 'transfer' },
        '転居': { romaji: 'tenkyo', meaning: 'moving house' },
        '引越': { romaji: 'hikkoshi', meaning: 'moving' },
        '出発': { romaji: 'shuppatsu', meaning: 'departure' },
        '到着': { romaji: 'touchaku', meaning: 'arrival' },
        '通過': { romaji: 'tsuuka', meaning: 'passage' },
        '経過': { romaji: 'keika', meaning: 'progress' },
        '進行': { romaji: 'shinkou', meaning: 'progress' },
        '前進': { romaji: 'zenshin', meaning: 'advance' },
        '後退': { romaji: 'koutai', meaning: 'retreat' },
        '上昇': { romaji: 'joushou', meaning: 'rise' },
        '下降': { romaji: 'kakou', meaning: 'descent' },
        '増加': { romaji: 'zouka', meaning: 'increase' },
        '減少': { romaji: 'genshou', meaning: 'decrease' },
        '拡大': { romaji: 'kakudai', meaning: 'expansion' },
        '縮小': { romaji: 'shukushou', meaning: 'reduction' },
        '延長': { romaji: 'enchou', meaning: 'extension' },
        '短縮': { romaji: 'tanshuku', meaning: 'shortening' },
        '拡張': { romaji: 'kakuchou', meaning: 'expansion' },
        '収縮': { romaji: 'shuushuku', meaning: 'contraction' },
        '伸縮': { romaji: 'shinshuku', meaning: 'expansion and contraction' },
        '膨張': { romaji: 'bouchou', meaning: 'expansion' },
        '圧縮': { romaji: 'asshuku', meaning: 'compression' },
        '圧迫': { romaji: 'appaku', meaning: 'pressure' },
        '圧力': { romaji: 'atsuryoku', meaning: 'pressure' },
        '重力': { romaji: 'juuryoku', meaning: 'gravity' },
        '引力': { romaji: 'inryoku', meaning: 'attraction' },
        '磁力': { romaji: 'jiryoku', meaning: 'magnetic force' },
        '電力': { romaji: 'denryoku', meaning: 'electric power' },
        '動力': { romaji: 'douryoku', meaning: 'motive power' },
        '馬力': { romaji: 'bariki', meaning: 'horsepower' },
        '能力': { romaji: 'nouryoku', meaning: 'ability' },
        '実力': { romaji: 'jitsuryoku', meaning: 'actual ability' },
        '力量': { romaji: 'rikiryou', meaning: 'ability/capacity' },
        '体力': { romaji: 'tairyoku', meaning: 'physical strength' },
        '精神': { romaji: 'seishin', meaning: 'spirit/mind' },
        '意識': { romaji: 'ishiki', meaning: 'consciousness' },
        '無意識': { romaji: 'muishiki', meaning: 'unconscious' },
        '感情': { romaji: 'kanjou', meaning: 'emotion' },
        '感覚': { romaji: 'kankaku', meaning: 'sensation' },
        '感動': { romaji: 'kandou', meaning: 'emotion/impression' },
        '印象': { romaji: 'inshou', meaning: 'impression' },
        '記憶': { romaji: 'kioku', meaning: 'memory' },
        '思い出': { romaji: 'omoide', meaning: 'memories' },
        '忘却': { romaji: 'boukyaku', meaning: 'oblivion' },
        '集中': { romaji: 'shuuchuu', meaning: 'concentration' },
        '注意': { romaji: 'chuui', meaning: 'attention' },
        '関心': { romaji: 'kanshin', meaning: 'interest' },
        '興味': { romaji: 'kyoumi', meaning: 'interest' },
        '好奇': { romaji: 'kouki', meaning: 'curiosity' },
        '疑問': { romaji: 'gimon', meaning: 'question/doubt' },
        '質問': { romaji: 'shitsumon', meaning: 'question' },
        '問題': { romaji: 'mondai', meaning: 'problem' },
        '課題': { romaji: 'kadai', meaning: 'task/assignment' },
        '宿題': { romaji: 'shukudai', meaning: 'homework' },
        '試験': { romaji: 'shiken', meaning: 'examination' },
        '検査': { romaji: 'kensa', meaning: 'inspection' },
        '診断': { romaji: 'shindan', meaning: 'diagnosis' },
        '判断': { romaji: 'handan', meaning: 'judgment' },
        '決定': { romaji: 'kettei', meaning: 'decision' },
        '選択': { romaji: 'sentaku', meaning: 'choice' },
        '選出': { romaji: 'senshutsu', meaning: 'selection' },
        '選考': { romaji: 'senkou', meaning: 'selection' },
        '採用': { romaji: 'saiyou', meaning: 'adoption/employment' },
        '雇用': { romaji: 'koyou', meaning: 'employment' },
        '就職': { romaji: 'shuushoku', meaning: 'getting a job' },
        '転職': { romaji: 'tenshoku', meaning: 'job change' },
        '退職': { romaji: 'taishoku', meaning: 'retirement' },
        '失業': { romaji: 'shitsugyou', meaning: 'unemployment' },
        '職業': { romaji: 'shokugyou', meaning: 'occupation' },
        '専門': { romaji: 'senmon', meaning: 'specialty' },
        '専攻': { romaji: 'senkou', meaning: 'major (study)' },
        '分野': { romaji: 'bunya', meaning: 'field' },
        '領域': { romaji: 'ryouiki', meaning: 'domain' },
        '範囲': { romaji: 'han-i', meaning: 'range' },
        '限界': { romaji: 'genkai', meaning: 'limit' },
        '制限': { romaji: 'seigen', meaning: 'restriction' },
        '規制': { romaji: 'kisei', meaning: 'regulation' },
        '規則': { romaji: 'kisoku', meaning: 'rule' },
        '法規': { romaji: 'houki', meaning: 'law and regulation' },
        '規定': { romaji: 'kitei', meaning: 'regulation' },
        '条件': { romaji: 'jouken', meaning: 'condition' },
        '状況': { romaji: 'joukyou', meaning: 'situation' },
        '状態': { romaji: 'joutai', meaning: 'state' },
        '場合': { romaji: 'baai', meaning: 'case' },
        '場面': { romaji: 'bamen', meaning: 'scene' },
        '現場': { romaji: 'genba', meaning: 'scene/site' },
        '会場': { romaji: 'kaijou', meaning: 'venue' },
        '現象': { romaji: 'genshou', meaning: 'phenomenon' },
        '事象': { romaji: 'jishou', meaning: 'event/phenomenon' },
        '事件': { romaji: 'jiken', meaning: 'incident' },
        '事故': { romaji: 'jiko', meaning: 'accident' },
        '災害': { romaji: 'saigai', meaning: 'disaster' },
        '災難': { romaji: 'sainan', meaning: 'disaster' },
        '困難': { romaji: 'konnan', meaning: 'difficulty' },
        '苦労': { romaji: 'kurou', meaning: 'hardship' },
        '苦痛': { romaji: 'kutsuu', meaning: 'pain' },
        '痛み': { romaji: 'itami', meaning: 'pain' },
        '悲しみ': { romaji: 'kanashimi', meaning: 'sadness' },
        '悲劇': { romaji: 'higeki', meaning: 'tragedy' },
        '喜び': { romaji: 'yorokobi', meaning: 'joy' },
        '楽しみ': { romaji: 'tanoshimi', meaning: 'pleasure' },
        '幸福': { romaji: 'koufuku', meaning: 'happiness' },
        '幸運': { romaji: 'kouun', meaning: 'good luck' },
        '運命': { romaji: 'unmei', meaning: 'fate' },
        '運動': { romaji: 'undou', meaning: 'movement/exercise' },
        '活動': { romaji: 'katsudou', meaning: 'activity' },
        '行動': { romaji: 'koudou', meaning: 'action/behavior' },
        '動作': { romaji: 'dousa', meaning: 'action/movement' },
        '操作': { romaji: 'sousa', meaning: 'operation' },
        '作業': { romaji: 'sagyou', meaning: 'work/operation' },
        '労働': { romaji: 'roudou', meaning: 'labor' },
        '勤務': { romaji: 'kinmu', meaning: 'duty/service' },
        '勤勉': { romaji: 'kinben', meaning: 'diligence' },
        '怠慢': { romaji: 'taiman', meaning: 'negligence' },
        '怠け': { romaji: 'namake', meaning: 'laziness' },
        '努力': { romaji: 'doryoku', meaning: 'effort' },
        '奮闘': { romaji: 'funtou', meaning: 'struggle' },
        '闘争': { romaji: 'tousou', meaning: 'struggle' },
        '競争': { romaji: 'kyousou', meaning: 'competition' },
        '競技': { romaji: 'kyougi', meaning: 'competition' },
        '勝負': { romaji: 'shoubu', meaning: 'match/contest' },
        '勝利': { romaji: 'shouri', meaning: 'victory' },
        '敗北': { romaji: 'haiboku', meaning: 'defeat' },
        '成功': { romaji: 'seikou', meaning: 'success' },
        '失敗': { romaji: 'shippai', meaning: 'failure' },
        '達成': { romaji: 'tassei', meaning: 'achievement' },
        '実現': { romaji: 'jitsugen', meaning: 'realization' },
        '実施': { romaji: 'jisshi', meaning: 'implementation' },
        '実行': { romaji: 'jikkou', meaning: 'execution' },
        '実践': { romaji: 'jissen', meaning: 'practice' },
        '実習': { romaji: 'jisshuu', meaning: 'practical training' },
        '訓練': { romaji: 'kunren', meaning: 'training' },
        '練習': { romaji: 'renshuu', meaning: 'practice' },
        '学習': { romaji: 'gakushuu', meaning: 'learning' },
        '研修': { romaji: 'kenshuu', meaning: 'training' },
        '修行': { romaji: 'shugyou', meaning: 'ascetic practice' },
        '修練': { romaji: 'shuuren', meaning: 'training' },
        '鍛錬': { romaji: 'tanren', meaning: 'discipline' },
        '修正': { romaji: 'shuusei', meaning: 'correction' },
        '改正': { romaji: 'kaisei', meaning: 'revision' },
        '訂正': { romaji: 'teisei', meaning: 'correction' },
        '修理': { romaji: 'shuuri', meaning: 'repair' },
        '修復': { romaji: 'shuufuku', meaning: 'restoration' },
        '復旧': { romaji: 'fukkyuu', meaning: 'restoration' },
        '回復': { romaji: 'kaifuku', meaning: 'recovery' },
        '治療': { romaji: 'chiryou', meaning: 'treatment' },
        '療法': { romaji: 'ryouhou', meaning: 'therapy' },
        '医療': { romaji: 'iryou', meaning: 'medical care' },
        '医学': { romaji: 'igaku', meaning: 'medicine' },
        '薬学': { romaji: 'yakugaku', meaning: 'pharmacy' },
        '看護': { romaji: 'kango', meaning: 'nursing' },
        '介護': { romaji: 'kaigo', meaning: 'nursing care' },
        '保護': { romaji: 'hogo', meaning: 'protection' },
        '保存': { romaji: 'hozon', meaning: 'preservation' },
        '保管': { romaji: 'hokan', meaning: 'storage' },
        '保険': { romaji: 'hoken', meaning: 'insurance' },
        '保証': { romaji: 'hoshou', meaning: 'guarantee' },
        '保障': { romaji: 'hoshou', meaning: 'guarantee' },
        '安全': { romaji: 'anzen', meaning: 'safety' },
        '安心': { romaji: 'anshin', meaning: 'peace of mind' },
        '安定': { romaji: 'antei', meaning: 'stability' },
        '平安': { romaji: 'heian', meaning: 'peace' },
        '平和': { romaji: 'heiwa', meaning: 'peace' },
        '平等': { romaji: 'byoudou', meaning: 'equality' },
        '公平': { romaji: 'kouhei', meaning: 'fairness' },
        '公正': { romaji: 'kousei', meaning: 'justice' },
        '公開': { romaji: 'koukai', meaning: 'public' },
        '公表': { romaji: 'kouhyou', meaning: 'announcement' },
        '発表': { romaji: 'happyou', meaning: 'presentation' },
        '表現': { romaji: 'hyougen', meaning: 'expression' },
        '表示': { romaji: 'hyouji', meaning: 'display' },
        '表明': { romaji: 'hyoumei', meaning: 'declaration' },
        '代表': { romaji: 'daihyou', meaning: 'representative' },
        '代理': { romaji: 'dairi', meaning: 'agent' },
        '代替': { romaji: 'daitai', meaning: 'substitute' },
        '代用': { romaji: 'daiyou', meaning: 'substitute' },
        '交代': { romaji: 'koutai', meaning: 'replacement' },
        '交換': { romaji: 'koukan', meaning: 'exchange' },
        '交流': { romaji: 'kouryuu', meaning: 'exchange' },
        '交際': { romaji: 'kousai', meaning: 'social relations' },
        '付き合い': { romaji: 'tsukiai', meaning: 'association' },
        '関係': { romaji: 'kankei', meaning: 'relationship' },
        '関連': { romaji: 'kanren', meaning: 'relation' },
        '連絡': { romaji: 'renraku', meaning: 'contact' },
        '連続': { romaji: 'renzoku', meaning: 'continuity' },
        '連合': { romaji: 'rengou', meaning: 'union' },
        '結合': { romaji: 'ketsugou', meaning: 'combination' },
        '結婚': { romaji: 'kekkon', meaning: 'marriage' },
        '結果': { romaji: 'kekka', meaning: 'result' },
        '結論': { romaji: 'ketsuron', meaning: 'conclusion' },
        '結末': { romaji: 'ketsumatsu', meaning: 'ending' },
        '終結': { romaji: 'shuuketsu', meaning: 'end' },
        '終了': { romaji: 'shuuryou', meaning: 'termination' },
        '完了': { romaji: 'kanryou', meaning: 'completion' },
        '完成': { romaji: 'kansei', meaning: 'completion' },
        '完全': { romaji: 'kanzen', meaning: 'perfect' },
        '完璧': { romaji: 'kanpeki', meaning: 'perfect' },
        '優秀': { romaji: 'yuushuu', meaning: 'excellent' },
        '優良': { romaji: 'yuuryou', meaning: 'excellent' },
        '優雅': { romaji: 'yuuga', meaning: 'elegant' },
        '優美': { romaji: 'yuubi', meaning: 'graceful' },
        '美しい': { romaji: 'utsukushii', meaning: 'beautiful' },
        '美術': { romaji: 'bijutsu', meaning: 'art' },
        '美学': { romaji: 'bigaku', meaning: 'aesthetics' },
        '美人': { romaji: 'bijin', meaning: 'beautiful person' },
        '美味': { romaji: 'bimi', meaning: 'delicious' },
        '美声': { romaji: 'bisei', meaning: 'beautiful voice' },
        '美貌': { romaji: 'bibou', meaning: 'beauty' },
        '容姿': { romaji: 'youshi', meaning: 'appearance' },
        '容貌': { romaji: 'youbou', meaning: 'appearance' },
        '外見': { romaji: 'gaiken', meaning: 'appearance' },
        '外観': { romaji: 'gaikan', meaning: 'appearance' },
        '外部': { romaji: 'gaibu', meaning: 'outside' },
        '外国': { romaji: 'gaikoku', meaning: 'foreign country' },
        '外交': { romaji: 'gaikou', meaning: 'diplomacy' },
        '内部': { romaji: 'naibu', meaning: 'inside' },
        '内容': { romaji: 'naiyou', meaning: 'content' },
        '内政': { romaji: 'naisei', meaning: 'domestic politics' },
        '内心': { romaji: 'naishin', meaning: 'inner heart' },
        '内面': { romaji: 'naimen', meaning: 'inner surface' },
        '心理': { romaji: 'shinri', meaning: 'psychology' },
        '心境': { romaji: 'shinkyou', meaning: 'mental state' },
        '心情': { romaji: 'shinjou', meaning: 'feeling' },
        '心配': { romaji: 'shinpai', meaning: 'worry' },
        '心得': { romaji: 'kokoroe', meaning: 'knowledge' },
        '心掛け': { romaji: 'kokorogake', meaning: 'attitude' },
        '心身': { romaji: 'shinshin', meaning: 'mind and body' },
        '身体': { romaji: 'shintai', meaning: 'body' },
        '身長': { romaji: 'shinchou', meaning: 'height' },
        '身分': { romaji: 'mibun', meaning: 'social status' },
        '身元': { romaji: 'mimoto', meaning: 'identity' },
        '正体': { romaji: 'shoutai', meaning: 'true identity' },
        '本体': { romaji: 'hontai', meaning: 'main body' },
        '全体': { romaji: 'zentai', meaning: 'whole' },
        '団体': { romaji: 'dantai', meaning: 'group' },
        '集団': { romaji: 'shuudan', meaning: 'group' },
        '集会': { romaji: 'shuukai', meaning: 'meeting' },
        '集合': { romaji: 'shuugou', meaning: 'gathering' },
        '会合': { romaji: 'kaigou', meaning: 'meeting' },
        '会議': { romaji: 'kaigi', meaning: 'conference' },
        '会談': { romaji: 'kaidan', meaning: 'conference' },
        '話し合い': { romaji: 'hanashiai', meaning: 'discussion' },
        '討論': { romaji: 'touron', meaning: 'debate' },
        '議論': { romaji: 'giron', meaning: 'argument' },
        '争論': { romaji: 'souron', meaning: 'dispute' },
        '論争': { romaji: 'ronsou', meaning: 'controversy' },
        '論理': { romaji: 'ronri', meaning: 'logic' },
        '理由': { romaji: 'riyuu', meaning: 'reason' },
        '理解': { romaji: 'rikai', meaning: 'understanding' },
        '理想': { romaji: 'risou', meaning: 'ideal' },
        '理念': { romaji: 'rinen', meaning: 'idea' },
        '概念': { romaji: 'gainen', meaning: 'concept' },
        '観念': { romaji: 'kannen', meaning: 'idea' },
        '思想': { romaji: 'shisou', meaning: 'thought' },
        '思考': { romaji: 'shikou', meaning: 'thinking' },
        '考慮': { romaji: 'kouryo', meaning: 'consideration' },
        '配慮': { romaji: 'hairyo', meaning: 'consideration' },
        '注意': { romaji: 'chuui', meaning: 'attention' },
        '警告': { romaji: 'keikoku', meaning: 'warning' },
        '警戒': { romaji: 'keikai', meaning: 'caution' },
        '用心': { romaji: 'youjin', meaning: 'caution' },
        '慎重': { romaji: 'shinchou', meaning: 'careful' },
        '丁寧': { romaji: 'teinei', meaning: 'polite' },
        '親切': { romaji: 'shinsetsu', meaning: 'kind' },
        '親しみ': { romaji: 'shitashimi', meaning: 'intimacy' },
        '親友': { romaji: 'shinyuu', meaning: 'close friend' },
        '友好': { romaji: 'yuukou', meaning: 'friendship' },
        '友愛': { romaji: 'yuuai', meaning: 'fraternal love' },
        '恋愛': { romaji: 'ren-ai', meaning: 'love' },
        '恋人': { romaji: 'koibito', meaning: 'lover' },
        '愛人': { romaji: 'aijin', meaning: 'lover' },
        '愛情': { romaji: 'aijou', meaning: 'love' },
        '愛護': { romaji: 'aigo', meaning: 'protection' },
        '愛好': { romaji: 'aikou', meaning: 'love/hobby' },
        '趣味': { romaji: 'shumi', meaning: 'hobby' },
        '興味': { romaji: 'kyoumi', meaning: 'interest' },
        '関心': { romaji: 'kanshin', meaning: 'interest' },
        '注目': { romaji: 'chuumoku', meaning: 'attention' },
        '評価': { romaji: 'hyouka', meaning: 'evaluation' },
        '評判': { romaji: 'hyouban', meaning: 'reputation' },
        '評論': { romaji: 'hyouron', meaning: 'criticism' },
        '批判': { romaji: 'hihan', meaning: 'criticism' },
        '批評': { romaji: 'hihyou', meaning: 'criticism' },
        '意見': { romaji: 'iken', meaning: 'opinion' },
        '感想': { romaji: 'kansou', meaning: 'impression' },
        '感激': { romaji: 'kangeki', meaning: 'deep emotion' },
        '感謝': { romaji: 'kansha', meaning: 'gratitude' },
        '感心': { romaji: 'kanshin', meaning: 'admiration' },
        '尊敬': { romaji: 'sonkei', meaning: 'respect' },
        '敬意': { romaji: 'keii', meaning: 'respect' },
        '礼儀': { romaji: 'reigi', meaning: 'etiquette' },
        '礼節': { romaji: 'reisetsu', meaning: 'courtesy' },
        '礼拝': { romaji: 'reihai', meaning: 'worship' },
        '祈り': { romaji: 'inori', meaning: 'prayer' },
        '祈願': { romaji: 'kigan', meaning: 'prayer' },
        '願い': { romaji: 'negai', meaning: 'wish' },
        '願望': { romaji: 'ganbou', meaning: 'desire' },
        '欲望': { romaji: 'yokubou', meaning: 'desire' },
        '欲求': { romaji: 'yokkyuu', meaning: 'desire' },
        '要求': { romaji: 'youkyuu', meaning: 'demand' },
        '要望': { romaji: 'youbou', meaning: 'request' },
        '希望': { romaji: 'kibou', meaning: 'hope' },
        '期待': { romaji: 'kitai', meaning: 'expectation' },
        '期限': { romaji: 'kigen', meaning: 'deadline' },
        '期間': { romaji: 'kikan', meaning: 'period' },
        '時期': { romaji: 'jiki', meaning: 'time/season' },
        '時代': { romaji: 'jidai', meaning: 'era' },
        '時刻': { romaji: 'jikoku', meaning: 'time' },
        '時間': { romaji: 'jikan', meaning: 'time' },
        '瞬間': { romaji: 'shunkan', meaning: 'moment' },
        '瞬時': { romaji: 'shunji', meaning: 'instant' },
        '一瞬': { romaji: 'isshun', meaning: 'moment' },
        '一時': { romaji: 'ichiji', meaning: 'temporary' },
        '一生': { romaji: 'isshou', meaning: 'lifetime' },
        '生涯': { romaji: 'shougai', meaning: 'lifetime' },
        '人生': { romaji: 'jinsei', meaning: 'life' },
        '生活': { romaji: 'seikatsu', meaning: 'life' },
        '生命': { romaji: 'seimei', meaning: 'life' },
        '生存': { romaji: 'seizon', meaning: 'survival' },
        '存在': { romaji: 'sonzai', meaning: 'existence' },
        '実在': { romaji: 'jitsuzai', meaning: 'real existence' },
        '現実': { romaji: 'genjitsu', meaning: 'reality' },
        '現状': { romaji: 'genjou', meaning: 'current situation' },
        '状況': { romaji: 'joukyou', meaning: 'situation' },
        '情況': { romaji: 'joukyou', meaning: 'situation' },
        '情報': { romaji: 'jouhou', meaning: 'information' },
        '報告': { romaji: 'houkoku', meaning: 'report' },
        '報道': { romaji: 'houdou', meaning: 'news' },
        '報知': { romaji: 'houchi', meaning: 'information' },
        '通報': { romaji: 'tsuuhou', meaning: 'report' },
        '通知': { romaji: 'tsuchi', meaning: 'notice' },
        '通信': { romaji: 'tsushin', meaning: 'communication' },
        '交信': { romaji: 'koushin', meaning: 'communication' },
        '信号': { romaji: 'shingou', meaning: 'signal' },
        '信頼': { romaji: 'shinrai', meaning: 'trust' },
        '信用': { romaji: 'shinyou', meaning: 'trust' },
        '信仰': { romaji: 'shinkou', meaning: 'faith' },
        '信念': { romaji: 'shinnen', meaning: 'belief' },
        '確信': { romaji: 'kakushin', meaning: 'conviction' },
        '自信': { romaji: 'jishin', meaning: 'confidence' },
        '自慢': { romaji: 'jiman', meaning: 'pride' },
        '自負': { romaji: 'jifu', meaning: 'pride' },
        '誇り': { romaji: 'hokori', meaning: 'pride' },
        '栄光': { romaji: 'eikou', meaning: 'glory' },
        '栄誉': { romaji: 'eiyo', meaning: 'honor' },
        '名誉': { romaji: 'meiyo', meaning: 'honor' },
        '名声': { romaji: 'meisei', meaning: 'reputation' },
        '声望': { romaji: 'seibou', meaning: 'reputation' },
        '人気': { romaji: 'ninki', meaning: 'popularity' },
        '人望': { romaji: 'jinbou', meaning: 'popularity' },
        '人材': { romaji: 'jinzai', meaning: 'human resources' },
        '人物': { romaji: 'jinbutsu', meaning: 'person' },
        '人格': { romaji: 'jinkaku', meaning: 'personality' },
        '人品': { romaji: 'jinpin', meaning: 'character' },
        '品格': { romaji: 'hinkaku', meaning: 'dignity' },
        '品位': { romaji: 'hini', meaning: 'dignity' },
        '品質': { romaji: 'hinshitsu', meaning: 'quality' },
        '品種': { romaji: 'hinshu', meaning: 'variety' },
        '種類': { romaji: 'shurui', meaning: 'kind' },
        '種族': { romaji: 'shuzoku', meaning: 'race' },
        '民族': { romaji: 'minzoku', meaning: 'ethnic group' },
        '国民': { romaji: 'kokumin', meaning: 'citizen' },
        '市民': { romaji: 'shimin', meaning: 'citizen' },
        '住民': { romaji: 'juumin', meaning: 'resident' },
        '国家': { romaji: 'kokka', meaning: 'nation' },
        '国土': { romaji: 'kokudo', meaning: 'national territory' },
        '領土': { romaji: 'ryoudo', meaning: 'territory' },
        '領域': { romaji: 'ryouiki', meaning: 'territory' },
        '地域': { romaji: 'chiiki', meaning: 'area' },
        '地方': { romaji: 'chihou', meaning: 'region' },
        '地区': { romaji: 'chiku', meaning: 'district' },
        '区域': { romaji: 'kuiki', meaning: 'area' },
        '区分': { romaji: 'kubun', meaning: 'division' },
        '分類': { romaji: 'bunrui', meaning: 'classification' },
        '分野': { romaji: 'bunya', meaning: 'field' }
    }
};

// For extreme sentence generation, we can define templates and word categories
// Not implemented yet


/*
// Example extreme templates for sentence generation
const extremeTemplates = [
    {
        template: 'わたしは{place}で{activity}をします。',
        romaji: 'watashi wa {place} de {activity} wo shimasu.',
        meaning: 'I {activity} at {place}.'
    },
    {
        template: '{time}に{food}を食べます。',
        romaji: '{time} ni {food} wo tabemasu.',
        meaning: 'I eat {food} at {time}.'
    },
    {
        template: '{weather}の日は{activity}をしません。',
        romaji: '{weather} no hi wa {activity} wo shimasen.',
        meaning: 'I don\'t {activity} on {weather} days.'
    },
    {
        template: '{person}と{place}に行きます。',
        romaji: '{person} to {place} ni ikimasu.',
        meaning: 'I go to {place} with {person}.'
    }
];

// Word categories for extreme sentence generation
const extremeWords = {
    place: ['がっこう', 'いえ', 'みせ', 'こうえん', 'えき'],
    activity: ['べんきょう', 'うんどう', 'りょうり', 'そうじ', 'しごと'],
    food: ['ごはん', 'パン', 'みず', 'おちゃ', 'くだもの'],
    time: ['あさ', 'ひる', 'よる', 'はちじ', 'くじ'],
    weather: ['あめ', 'ゆき', 'はれ', 'くもり', 'かぜ'],
    person: ['ともだち', 'せんせい', 'かぞく', 'がくせい', 'ひと']
};
*/