// Enhanced kanji data with readings and meanings
const kanjiData = {
    // Basic kanji (Grade 1-2 level)
    '一': { kunyomi: 'ひと', onyomi: 'イチ', meaning: 'one' },
    '二': { kunyomi: 'ふた', onyomi: 'ニ', meaning: 'two' },
    '三': { kunyomi: 'みっ', onyomi: 'サン', meaning: 'three' },
    '四': { kunyomi: 'よん', onyomi: 'シ', meaning: 'four' },
    '五': { kunyomi: 'いつ', onyomi: 'ゴ', meaning: 'five' },
    '六': { kunyomi: 'むっ', onyomi: 'ロク', meaning: 'six' },
    '七': { kunyomi: 'なな', onyomi: 'シチ', meaning: 'seven' },
    '八': { kunyomi: 'やっ', onyomi: 'ハチ', meaning: 'eight' },
    '九': { kunyomi: 'ここの', onyomi: 'キュウ', meaning: 'nine' },
    '十': { kunyomi: 'とお', onyomi: 'ジュウ', meaning: 'ten' },
    '百': { kunyomi: 'もも', onyomi: 'ヒャク', meaning: 'hundred' },
    '千': { kunyomi: 'ち', onyomi: 'セン', meaning: 'thousand' },
    '万': { kunyomi: 'よろず', onyomi: 'マン', meaning: 'ten thousand' },
    
    // Time and calendar
    '日': { kunyomi: 'ひ', onyomi: 'ニチ', meaning: 'day/sun' },
    '月': { kunyomi: 'つき', onyomi: 'ゲツ', meaning: 'month/moon' },
    '年': { kunyomi: 'とし', onyomi: 'ネン', meaning: 'year' },
    '時': { kunyomi: 'とき', onyomi: 'ジ', meaning: 'time' },
    '週': { kunyomi: '', onyomi: 'シュウ', meaning: 'week' },
    '今': { kunyomi: 'いま', onyomi: 'コン', meaning: 'now' },
    '前': { kunyomi: 'まえ', onyomi: 'ゼン', meaning: 'before' },
    '後': { kunyomi: 'あと', onyomi: 'ゴ', meaning: 'after' },
    '毎': { kunyomi: 'まい', onyomi: 'マイ', meaning: 'every' },
    
    // People and family
    '人': { kunyomi: 'ひと', onyomi: 'ジン', meaning: 'person' },
    '子': { kunyomi: 'こ', onyomi: 'シ', meaning: 'child' },
    '女': { kunyomi: 'おんな', onyomi: 'ジョ', meaning: 'woman' },
    '男': { kunyomi: 'おとこ', onyomi: 'ダン', meaning: 'man' },
    '父': { kunyomi: 'ちち', onyomi: 'フ', meaning: 'father' },
    '母': { kunyomi: 'はは', onyomi: 'ボ', meaning: 'mother' },
    '兄': { kunyomi: 'あに', onyomi: 'キョウ', meaning: 'older brother' },
    '弟': { kunyomi: 'おとうと', onyomi: 'テイ', meaning: 'younger brother' },
    '姉': { kunyomi: 'あね', onyomi: 'シ', meaning: 'older sister' },
    '妹': { kunyomi: 'いもうと', onyomi: 'マイ', meaning: 'younger sister' },
    '友': { kunyomi: 'とも', onyomi: 'ユウ', meaning: 'friend' },
    '先': { kunyomi: 'さき', onyomi: 'セン', meaning: 'ahead/prior' },
    '生': { kunyomi: 'い', onyomi: 'セイ', meaning: 'life/birth' },
    
    // Body parts
    '手': { kunyomi: 'て', onyomi: 'シュ', meaning: 'hand' },
    '足': { kunyomi: 'あし', onyomi: 'ソク', meaning: 'foot/leg' },
    '目': { kunyomi: 'め', onyomi: 'モク', meaning: 'eye' },
    '耳': { kunyomi: 'みみ', onyomi: 'ジ', meaning: 'ear' },
    '口': { kunyomi: 'くち', onyomi: 'コウ', meaning: 'mouth' },
    '鼻': { kunyomi: 'はな', onyomi: 'ビ', meaning: 'nose' },
    '頭': { kunyomi: 'あたま', onyomi: 'トウ', meaning: 'head' },
    '心': { kunyomi: 'こころ', onyomi: 'シン', meaning: 'heart/mind' },
    '体': { kunyomi: 'からだ', onyomi: 'タイ', meaning: 'body' },
    
    // Nature
    '山': { kunyomi: 'やま', onyomi: 'サン', meaning: 'mountain' },
    '川': { kunyomi: 'かわ', onyomi: 'セン', meaning: 'river' },
    '海': { kunyomi: 'うみ', onyomi: 'カイ', meaning: 'sea' },
    '空': { kunyomi: 'そら', onyomi: 'クウ', meaning: 'sky' },
    '雲': { kunyomi: 'くも', onyomi: 'ウン', meaning: 'cloud' },
    '雨': { kunyomi: 'あめ', onyomi: 'ウ', meaning: 'rain' },
    '雪': { kunyomi: 'ゆき', onyomi: 'セツ', meaning: 'snow' },
    '風': { kunyomi: 'かぜ', onyomi: 'フウ', meaning: 'wind' },
    '火': { kunyomi: 'ひ', onyomi: 'カ', meaning: 'fire' },
    '水': { kunyomi: 'みず', onyomi: 'スイ', meaning: 'water' },
    '土': { kunyomi: 'つち', onyomi: 'ド', meaning: 'earth/soil' },
    '木': { kunyomi: 'き', onyomi: 'モク', meaning: 'tree/wood' },
    '花': { kunyomi: 'はな', onyomi: 'カ', meaning: 'flower' },
    '草': { kunyomi: 'くさ', onyomi: 'ソウ', meaning: 'grass' },
    '石': { kunyomi: 'いし', onyomi: 'セキ', meaning: 'stone' },
    
    // Animals
    '犬': { kunyomi: 'いぬ', onyomi: 'ケン', meaning: 'dog' },
    '猫': { kunyomi: 'ねこ', onyomi: 'ビョウ', meaning: 'cat' },
    '鳥': { kunyomi: 'とり', onyomi: 'チョウ', meaning: 'bird' },
    '魚': { kunyomi: 'さかな', onyomi: 'ギョ', meaning: 'fish' },
    '馬': { kunyomi: 'うま', onyomi: 'バ', meaning: 'horse' },
    '牛': { kunyomi: 'うし', onyomi: 'ギュウ', meaning: 'cow' },
    '虫': { kunyomi: 'むし', onyomi: 'チュウ', meaning: 'insect' },
    
    // Places and buildings
    '家': { kunyomi: 'いえ', onyomi: 'カ', meaning: 'house' },
    '国': { kunyomi: 'くに', onyomi: 'コク', meaning: 'country' },
    '町': { kunyomi: 'まち', onyomi: 'チョウ', meaning: 'town' },
    '村': { kunyomi: 'むら', onyomi: 'ソン', meaning: 'village' },
    '市': { kunyomi: 'いち', onyomi: 'シ', meaning: 'city' },
    '学': { kunyomi: 'まな', onyomi: 'ガク', meaning: 'learn' },
    '校': { kunyomi: '', onyomi: 'コウ', meaning: 'school' },
    '店': { kunyomi: 'みせ', onyomi: 'テン', meaning: 'store' },
    '駅': { kunyomi: 'えき', onyomi: 'エキ', meaning: 'station' },
    '病': { kunyomi: 'やまい', onyomi: 'ビョウ', meaning: 'illness' },
    '院': { kunyomi: '', onyomi: 'イン', meaning: 'institution' },
    '車': { kunyomi: 'くるま', onyomi: 'シャ', meaning: 'car' },
    '道': { kunyomi: 'みち', onyomi: 'ドウ', meaning: 'road/way' },
    '門': { kunyomi: 'もん', onyomi: 'モン', meaning: 'gate' },
    '橋': { kunyomi: 'はし', onyomi: 'キョウ', meaning: 'bridge' },
    
    // Actions and verbs
    '行': { kunyomi: 'い', onyomi: 'コウ', meaning: 'go' },
    '来': { kunyomi: 'く', onyomi: 'ライ', meaning: 'come' },
    '帰': { kunyomi: 'かえ', onyomi: 'キ', meaning: 'return' },
    '見': { kunyomi: 'み', onyomi: 'ケン', meaning: 'see' },
    '聞': { kunyomi: 'き', onyomi: 'ブン', meaning: 'hear' },
    '読': { kunyomi: 'よ', onyomi: 'ドク', meaning: 'read' },
    '書': { kunyomi: 'か', onyomi: 'ショ', meaning: 'write' },
    '話': { kunyomi: 'はな', onyomi: 'ワ', meaning: 'speak' },
    '食': { kunyomi: 'た', onyomi: 'ショク', meaning: 'eat' },
    '飲': { kunyomi: 'の', onyomi: 'イン', meaning: 'drink' },
    '買': { kunyomi: 'か', onyomi: 'バイ', meaning: 'buy' },
    '売': { kunyomi: 'う', onyomi: 'バイ', meaning: 'sell' },
    '作': { kunyomi: 'つく', onyomi: 'サク', meaning: 'make' },
    '立': { kunyomi: 'た', onyomi: 'リツ', meaning: 'stand' },
    '座': { kunyomi: 'すわ', onyomi: 'ザ', meaning: 'sit' },
    '走': { kunyomi: 'はし', onyomi: 'ソウ', meaning: 'run' },
    '歩': { kunyomi: 'ある', onyomi: 'ホ', meaning: 'walk' },
    '止': { kunyomi: 'と', onyomi: 'シ', meaning: 'stop' },
    '休': { kunyomi: 'やす', onyomi: 'キュウ', meaning: 'rest' },
    '働': { kunyomi: 'はたら', onyomi: 'ドウ', meaning: 'work' },
    '勉': { kunyomi: '', onyomi: 'ベン', meaning: 'diligence' },
    '強': { kunyomi: 'つよ', onyomi: 'キョウ', meaning: 'strong' },
    '教': { kunyomi: 'おし', onyomi: 'キョウ', meaning: 'teach' },
    '習': { kunyomi: 'なら', onyomi: 'シュウ', meaning: 'learn' },
    '思': { kunyomi: 'おも', onyomi: 'シ', meaning: 'think' },
    '考': { kunyomi: 'かんが', onyomi: 'コウ', meaning: 'consider' },
    '知': { kunyomi: 'し', onyomi: 'チ', meaning: 'know' },
    '分': { kunyomi: 'わ', onyomi: 'ブン', meaning: 'divide/understand' },
    '出': { kunyomi: 'で', onyomi: 'シュツ', meaning: 'exit' },
    '入': { kunyomi: 'はい', onyomi: 'ニュウ', meaning: 'enter' },
    '上': { kunyomi: 'うえ', onyomi: 'ジョウ', meaning: 'above' },
    '下': { kunyomi: 'した', onyomi: 'カ', meaning: 'below' },
    '中': { kunyomi: 'なか', onyomi: 'チュウ', meaning: 'inside' },
    '外': { kunyomi: 'そと', onyomi: 'ガイ', meaning: 'outside' },
    '右': { kunyomi: 'みぎ', onyomi: 'ウ', meaning: 'right' },
    '左': { kunyomi: 'ひだり', onyomi: 'サ', meaning: 'left' },
    '北': { kunyomi: 'きた', onyomi: 'ホク', meaning: 'north' },
    '南': { kunyomi: 'みなみ', onyomi: 'ナン', meaning: 'south' },
    '東': { kunyomi: 'ひがし', onyomi: 'トウ', meaning: 'east' },
    '西': { kunyomi: 'にし', onyomi: 'セイ', meaning: 'west' },
    
    // Adjectives and descriptions
    '大': { kunyomi: 'おお', onyomi: 'ダイ', meaning: 'big' },
    '小': { kunyomi: 'ちい', onyomi: 'ショウ', meaning: 'small' },
    '高': { kunyomi: 'たか', onyomi: 'コウ', meaning: 'high/tall' },
    '低': { kunyomi: 'ひく', onyomi: 'テイ', meaning: 'low' },
    '長': { kunyomi: 'なが', onyomi: 'チョウ', meaning: 'long' },
    '短': { kunyomi: 'みじか', onyomi: 'タン', meaning: 'short' },
    '新': { kunyomi: 'あたら', onyomi: 'シン', meaning: 'new' },
    '古': { kunyomi: 'ふる', onyomi: 'コ', meaning: 'old' },
    '若': { kunyomi: 'わか', onyomi: 'ジャク', meaning: 'young' },
    '多': { kunyomi: 'おお', onyomi: 'タ', meaning: 'many' },
    '少': { kunyomi: 'すく', onyomi: 'ショウ', meaning: 'few' },
    '早': { kunyomi: 'はや', onyomi: 'ソウ', meaning: 'early' },
    '遅': { kunyomi: 'おそ', onyomi: 'チ', meaning: 'late' },
    '近': { kunyomi: 'ちか', onyomi: 'キン', meaning: 'near' },
    '遠': { kunyomi: 'とお', onyomi: 'エン', meaning: 'far' },
    '明': { kunyomi: 'あか', onyomi: 'メイ', meaning: 'bright' },
    '暗': { kunyomi: 'くら', onyomi: 'アン', meaning: 'dark' },
    '白': { kunyomi: 'しろ', onyomi: 'ハク', meaning: 'white' },
    '黒': { kunyomi: 'くろ', onyomi: 'コク', meaning: 'black' },
    '赤': { kunyomi: 'あか', onyomi: 'セキ', meaning: 'red' },
    '青': { kunyomi: 'あお', onyomi: 'セイ', meaning: 'blue' },
    '黄': { kunyomi: 'き', onyomi: 'オウ', meaning: 'yellow' },
    '緑': { kunyomi: 'みどり', onyomi: 'リョク', meaning: 'green' },
    
    // Objects and things
    '本': { kunyomi: 'ほん', onyomi: 'ホン', meaning: 'book' },
    '紙': { kunyomi: 'かみ', onyomi: 'シ', meaning: 'paper' },
    '字': { kunyomi: 'じ', onyomi: 'ジ', meaning: 'character' },
    '文': { kunyomi: 'ふみ', onyomi: 'ブン', meaning: 'sentence' },
    '名': { kunyomi: 'な', onyomi: 'メイ', meaning: 'name' },
    '音': { kunyomi: 'おと', onyomi: 'オン', meaning: 'sound' },
    '声': { kunyomi: 'こえ', onyomi: 'セイ', meaning: 'voice' },
    '言': { kunyomi: 'い', onyomi: 'ゲン', meaning: 'say' },
    '語': { kunyomi: 'かた', onyomi: 'ゴ', meaning: 'language' },
    '電': { kunyomi: '', onyomi: 'デン', meaning: 'electricity' },
    '気': { kunyomi: 'き', onyomi: 'キ', meaning: 'spirit/energy' },
    '物': { kunyomi: 'もの', onyomi: 'ブツ', meaning: 'thing' },
    '品': { kunyomi: 'しな', onyomi: 'ヒン', meaning: 'goods' },
    '用': { kunyomi: 'もち', onyomi: 'ヨウ', meaning: 'use' },
    '方': { kunyomi: 'かた', onyomi: 'ホウ', meaning: 'direction/way' },
    '間': { kunyomi: 'あいだ', onyomi: 'カン', meaning: 'interval' },
    '所': { kunyomi: 'ところ', onyomi: 'ショ', meaning: 'place' },
    '場': { kunyomi: 'ば', onyomi: 'ジョウ', meaning: 'place' },
    '力': { kunyomi: 'ちから', onyomi: 'リキ', meaning: 'power' },
    '元': { kunyomi: 'もと', onyomi: 'ゲン', meaning: 'origin' },
    '金': { kunyomi: 'かね', onyomi: 'キン', meaning: 'gold/money' },
    '銀': { kunyomi: 'ぎん', onyomi: 'ギン', meaning: 'silver' },
    '玉': { kunyomi: 'たま', onyomi: 'ギョク', meaning: 'ball/gem' },
    '宝': { kunyomi: 'たから', onyomi: 'ホウ', meaning: 'treasure' },
    '服': { kunyomi: 'ふく', onyomi: 'フク', meaning: 'clothes' },
    '靴': { kunyomi: 'くつ', onyomi: 'カ', meaning: 'shoes' },
    '帽': { kunyomi: 'ぼう', onyomi: 'ボウ', meaning: 'hat' },
    '袋': { kunyomi: 'ふくろ', onyomi: 'タイ', meaning: 'bag' },
    '箱': { kunyomi: 'はこ', onyomi: 'ハコ', meaning: 'box' },
    '机': { kunyomi: 'つくえ', onyomi: 'キ', meaning: 'desk' },
    '椅': { kunyomi: 'いす', onyomi: 'イ', meaning: 'chair' },
    '窓': { kunyomi: 'まど', onyomi: 'ソウ', meaning: 'window' },
    '戸': { kunyomi: 'と', onyomi: 'コ', meaning: 'door' },
    '鍵': { kunyomi: 'かぎ', onyomi: 'ケン', meaning: 'key' },
    '刀': { kunyomi: 'かたな', onyomi: 'トウ', meaning: 'sword' },
    '弓': { kunyomi: 'ゆみ', onyomi: 'キュウ', meaning: 'bow' },
    '矢': { kunyomi: 'や', onyomi: 'シ', meaning: 'arrow' },
    '船': { kunyomi: 'ふね', onyomi: 'セン', meaning: 'ship' },
    '飛': { kunyomi: 'と', onyomi: 'ヒ', meaning: 'fly' },
    '歌': { kunyomi: 'うた', onyomi: 'カ', meaning: 'song' },
    '画': { kunyomi: '', onyomi: 'ガ', meaning: 'picture' },
    '絵': { kunyomi: 'え', onyomi: 'カイ', meaning: 'picture' },
    '写': { kunyomi: 'うつ', onyomi: 'シャ', meaning: 'copy' },
    '真': { kunyomi: 'ま', onyomi: 'シン', meaning: 'true' }
};